oamg/leapp

ansible/centos6-guest-lamp/ansible/roles/init/tasks/main.yml
ansible/centos7-guest-lamp/ansible/roles/init/tasks/main.yml
ansible/centos7-target/ansible/roles/init/tasks/main.yml
leapp-tool.py

Merged version of #11 only had the integration test changes, as I ran `git add .` from the wrong directory.

Finish removing vagrant ssh hack

---

ansible/centos6-guest-lamp/ansible/roles/init/tasks/main.yml
ansible/centos7-guest-lamp/ansible/roles/init/tasks/main.yml
ansible/centos7-target/ansible/roles/init/tasks/main.yml
cockpit/leapp.html

- load SSH key into demo VMs correctly
- improve the plugin output when running the migration command

Partial fix for demo execution

---

cockpit/leapp.html
integration-tests/features/environment.py
integration-tests/features/steps/common.py
integration-tests/vmdefs/centos6-guest-httpd/Vagrantfile
integration-tests/vmdefs/centos7-target/Vagrantfile
leapp-tool.py

Fixes issue #20 by updating the Cockpit plugin to explicitly forward the PHP MyAdmin port rather than the default HTTP port.
Also fixes issues #18 by using `leapp-tests` as a disambiguator for the integration testing VM and host names.

Fix errors in demo

---

cockpit/leapp.html

cockpit: Add missing parameter `data` for list_local_vms_fail

---

centos-ci/jobs/integration_test.yml

we were missing a dash in front of the shell builder

---

centos-ci/jobs/integration_test.yml

A comment against a PR with the phrase 'Jenkins Test' will trigger a build of the integration-tests

add a trigger phrase: .*Jenkins Test.*

---

cockpit/leapp.html
integration-tests/README.md
integration-tests/features/destroy-containers.feature
integration-tests/features/environment.py
integration-tests/features/steps/destroy_containers.py
src/leappto/__init__.py
src/leappto/cli.py
src/leappto/providers/libvirt_provider.py
src/setup.py

first three points from https://github.com/leapp-to/prototype/issues/43#issue-220824432

UI demo - new layout

---

cockpit/leapp.html

This PR contains:
- Simplify the information displayed in Cockpit
- Remove the "reprovision" button
- Centralized migration button

Make ui user friendly

---

README.md
cockpit/manifest.json

Change cockpit plugin label, Kernel Flexibility is confusing

NOJIRA: Change cockpit plugin label, Kernel Flexibility is confusing

---

src/leappto/cli.py
src/leappto/version.py
src/setup.py

Fixes #69 version reporting in leapp-tool

---

centos-ci/jobs/integration_test.yml

Add vinzenz to the admin list

---

ansible_roles/ovirt-guest-agent/tasks/main.yml
ansible_roles/qemu-guest-agent/tasks/main.yml
demo/vmdefs/centos6-drools-guest/Vagrantfile
demo/vmdefs/centos6-drools-guest/playbook.yml
demo/vmdefs/centos6-guest/Vagrantfile
demo/vmdefs/centos6-guest/playbook.yml
demo/vmdefs/centos7-target/Vagrantfile
demo/vmdefs/centos7-target/playbook.yml
src/leappto/providers/libvirt_provider.py

Hostname retrieval

---

cockpit/leapp.html

inform users that they have to wait to see result after migrate cmd

inform users about lag

---

README.md
src/leappto/providers/libvirt_provider.py
src/setup.py

This PR introduces a new fallback mechanism to use vagrant SSH  to scan the machine for OS info, ips and hostname

Vagrant ssh scan

---

cockpit/leapp.html

Previously clicking on the text for the machines in the UI wasn't selecting the radios
This PR fixes that

Clickable machine labels

---

CONTRIBUTING.md

These are modeled on the guidelines used by the
fabric8-analytics project:
* https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/CONTRIBUTING.md

Add initial contributing guidelines

---

centos-ci/bootstrap.sh
integration-tests/.gitignore

- don't emit ANSI colour control codes in logs
- emit JUnit compatible XML test reports

Tidy up CI testing output

---

cockpit/config.json
cockpit/leapp.html
leapp.spec

This fixes two things:
- A configurable tool location via cockpit/config.json
- Version reporting and this resolves #70

Cockpit config + Version Info display

---

AUTHORS
cockpit/leapp.html
integration-tests/features/leapp_testing/__init__.py
integration-tests/features/port-inspect.feature
integration-tests/features/steps/port_inspect.py
src/leappto/cli.py

Manual port mapping

---

cockpit/config.json
cockpit/leapp.html
integration-tests/features/cockpit-demo.feature
integration-tests/features/steps/cockpit_demo.py
leapp.spec

To ensure the plugin continues to work correctly
with this change, the plugin integration tests
have also been updated to cover a full migration
command.

Remove hardcoded user from Cockpit plugin

---

integration-tests/features/default-port-detection.feature
integration-tests/features/steps/default-port-detection.py
src/leappto/cli.py

I also did a bit refactoring of the code in order to make it bit simpler

CLI stop execution when user specify used port

---

centos-ci/bootstrap.sh
leapp.spec

Also fixes current tito build errors

Build RPM in pre-merge CI

---

src/leappto/cli.py

Use sys.exit instead of exit in cli.py

---

centos-ci/ansible/callback_plugins/profile_tasks.py
centos-ci/bootstrap.sh

add timestamps and command time duration execution reporting

TRELLO-163: add timestamps 

---

cockpit/leapp.html

Using ID based on port number could lead to duplicate issues while when manual port mapping is created

Removed IDs from checkbox in port list.

---

cockpit/leapp.html
integration-tests/features/cockpit-demo.feature
integration-tests/features/httpd-stateless.feature
integration-tests/features/steps/cockpit_demo.py

- updated for the new app import workflow
- updated to use ssh-agent for authentication
(WIP as the ssh-agent part isn't working yet)

Restore Cockpit plugin test

---

tox.ini

add  tox config file with line length

add  tox config file with line length

---

leapp.spec

update CLI version during RPM build

update CLI version during RPM build

---

docs/source/getstarted.rst

update readme to reflect the latest situation

update readme to reflect the latest situation

---

src/leappto/cli.py

This fixes #242
I decided that the cmd line parameter will be rather for 0.1.1

cli: Disable interfering init services on el6

---

ansible_roles/init/tasks/main.yml
centos-ci/bootstrap.sh
docs/source/integration-tests.rst
integration-tests/features/environment.py
integration-tests/features/leapp_testing/__init__.py
integration-tests/features/steps/cockpit_demo.py

Test Leapp RPM in CI

---

src/leappto/cli.py

Added --no-freeze option since it might cause issues. I am trying to still figure out why exactly i dies, but this should be a workaround fix for 0.1

Added --no-freeze option into migrate command

---

README.md

preview of README https://github.com/vmindru/leapp/tree/new_demo_gif

NOJIRA: new demo gif

---

src/leappto/cli.py

Sometimes I've encountered that fsck wants to run during container startup. This of course does not work and fsck asks interactively what to do, blocking the whole boot process.
This change prevents it by creating the /fastboot file in the target container which causes fsck to be
skipped. It is created outside the container and r/o mounted there to prevent
the container from removing it. At the same time create also /.nolvm, which
prevents LVM configuration.
It would be preferable to get rid of the whole /etc/rc.sysinit script, whose majority does not make sense in a container environment, but this I found too invasive.

Prevent fsck from running.

---

cockpit/leapp.html

Added form for specifying excluded paths in UI

Ui exclude paths

---

centos-ci/bootstrap.sh

I am opening this PR since our CI is currently broken and we need to push few PRs through, which are at this moment not related to the functionality.

Disable CI till the time it will be completely fixed

---

docs/source/devenv-install.md

I think that the following sentence should be reworded to be more descriptive:
snactor: This tool is designed to get quickly started with leapp actor development

Fix language in devenv-install.md

---

leapp/repository/__init__.py
leapp/repository/actor_definition.py
leapp/repository/definition.py
leapp/repository/loader.py
leapp/repository/manager.py
leapp/repository/scan.py

Added docstrings to Repository related files

Repository documentation

---

docs/source/first-actor.md
docs/source/working-with-workflows.md

Cosmetic changes on documentation.

Replace tabs with spaces in example codes from docs

---

leapp/cli/upgrade/__init__.py

Join several styles of writing --whitelist-experimental - several occurrences and/or comma separated list of actors

CLI upgrade --whitelist-experimental: Accept comma separated list

---

leapp/cli/upgrade/__init__.py

Previously when running leapp upgrade flags that have been passed
during the initial run, were not restored when trying to resume.
As a result of that, using --whitelist-experimental or --debug
on the command line were not respected within the initram phase
any more because those flags were forgotten.
This patch introduces a storing of those flags and passing them
on to the other phases with the same execution context (session).

upgrade: Remember commandline flags when resuming

---

Makefile

Fix timestamp final

---

docs/source/messaging.md

- in the tutorial about actor messaging

Mention clearing saved messages by snactor

---

AUTHORS
docs/source/pydoc/leapp.libraries.rst
docs/source/pydoc/leapp.libraries.stdlib.rst
leapp/libraries/stdlib/__init__.py
tests/scripts/test_stdlib.py

leapp.libraries.stdlib library created
- represents a location for functions that otherwise would be/were defined multiple times across leapp actors. And at the same time incorporated functions are really useful for other actors.
Library leapp.libraries.stdlib now consists of:
Function
- call - supporting python2/python3 (six module)

WIP: Introduction of leapp.libraries.stdlib library

---

leapp/libraries/stdlib/__init__.py
tests/scripts/test_stdlib.py

stdlib: check_output should be call

---

leapp/repository/manager.py

- to better explain the purpose of its attributes

Update RepositoryManager class comments

---

leapp/snactor/fixture.py

pytest.hookimpl was introduced in pytest 2.8 - Older version would break
on the fact that we use the decorator. This patch will make the
definition of the hook conditional based on the existance of the
decorator in the module.
Fixes: https://github.com/oamg/leapp/issues/407

snactor.fixture: Conditional pyfunc hook

---

leapp/actors/__init__.py
leapp/dialogs/components.py
leapp/dialogs/dialog.py
leapp/models/__init__.py
leapp/models/fields/__init__.py
leapp/snactor/commands/discover.py
leapp/workflows/__init__.py
leapp/workflows/flags.py
leapp/workflows/phases.py
leapp/workflows/policies.py
leapp/workflows/tagfilters.py

This PR adds support for more items to be serializable, which will help with discovery and automated tooling for extracting information from actors, dialogs, models etc etc

Extended serialization support

---

res/schema/migrations/0001-add-execution-kind-column.sql

User schema version fix. The current user sql chema version is 2.

Fix SQL Schema version

---

leapp/__init__.py
man/leapp.1
packaging/leapp.spec

- Models has been refactored to be more comprehensible and reliable
- Introduced standard library
- Introduced the actor convenience api for actors and repository libraries
- Added localization support
- Extended serialization support
- Added exception to be able to stop actor execution

Release 0.5.0

---

leapp/libraries/stdlib/__init__.py
leapp/libraries/stdlib/call.py
leapp/utils/audit/__init__.py
tests/scripts/test_audit.py
tests/scripts/test_stdlib_call_audit.py

Leapp stdlib Call function enrichment with audit data generation and storage.
Names of these new_... functions are to be changed to just simply to call, checked_call, later when replacing the current call definition.

Ext program exec function leapp stdlib call with audit

---

leapp/cli/__init__.py
leapp/cli/upgrade/__init__.py
leapp/libraries/stdlib/__init__.py
leapp/logger/__init__.py
leapp/snactor/__init__.py

Add new command line argument "--verbose"
- Change the log level to INFO in verbose and DEBUG in "--debug"

Add new verbose mode

---

leapp/cli/__init__.py
leapp/cli/report/__init__.py
leapp/cli/upgrade/__init__.py
leapp/models/__init__.py
leapp/reporting/__init__.py
leapp/topics/__init__.py
leapp/utils/report.py
packaging/leapp.spec

This is WIP PR for introducing new reporting models and report command.
Comments are highly appreciated.
Require Repo PR: oamg/leapp-repository/pull/86

New reporting

---

man/leapp.1

Relates to: https://github.com/oamg/leapp/pull/472

Add return codes to man page

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

snactor
- `repo new` subcommand: display message if directory with same name exists
- `discover subcommand`: fix wrong path
- `workflow run` subcommand: introduce `--save-output` parameter
- fix cryptic message without user repo config
- show global repos in repo list
- fix trace on topic creation
stdlib
- make api directly available in stdlib
- external program exec function - audit data generation and storage
models
- introduction of the JSON field type
new debug and verbose modes
new reporting capabilities
change default loglevel to ERROR

Release v0.6.0

---

leapp/libraries/stdlib/__init__.py

Previous default _logging_handler is not compatible with Python3.
To fix that, we use __write_fd function which take care about
the raw output.
TODO: tests are missing and maybe will not be delivered as the
solution is probably temporary.

stdlib: Py 2 and 3 compatible __logging_handler

---

.flake8
Makefile
leapp/libraries/stdlib/call.py
tests/data/call_data/panagrams
tests/scripts/test_stdlib_call.py

* Input data are now decoded using incremental decoder
* Docstring now reflects parameters better
* Add tests for various language pangrams
Fixes #488

Fix _call unicode issues

---

.github/ISSUE_TEMPLATE/bug_report.md
leapp/cli/upgrade/__init__.py
leapp/logger/__init__.py

This PR  will archive old logs in `/var/log/leapp/archive` and create the logs directory structure.
```
/var/log/leapp/dnf-debugdata/
/var/log/leapp/leapp-upgrade.log
/var/log/leapp/leapp-report.txt
/var/log/leapp/dnf-plugin-data.txt
```

Changes to archive and create logs structure

---

.flake8
.pylintrc
Makefile
leapp/cli/__main__.py
leapp/compat.py
leapp/config.py
leapp/reporting/__init__.py
leapp/repository/__init__.py
leapp/snactor/commands/workflow/run.py
leapp/snactor/fixture.py
leapp/utils/i18n.py
requirements-tests.txt
setup.cfg
tests/scripts/test_actor_api.py
tests/scripts/test_messaging.py
tests/scripts/test_repository.py
tests/scripts/test_repository_actor_definition.py
tests/scripts/test_snactor.py
tests/scripts/test_stdlib_call.py
tests/scripts/test_utils_meta.py
tests/scripts/test_utils_project.py
tox.ini

Added a naive pylint config with everything
disabled.
The following commits will enable a checking
option following a necessary code refactor.

lint: introduce lint check with pylint

---

docs/source/actor-rhel7-to-rhel8.md
docs/source/tutorials.rst

- This documentation is to help the developer start contributing to the Leapp project by writing actors to upgrade from RHEL7 to RHEL8.

Add documentation of how to write an actor to upgrade process.

---

leapp/utils/clicmd.py

Related to https://github.com/oamg/leapp/issues/474.

Print usage to stderr

---

leapp/cli/upgrade/__init__.py
leapp/config.py
leapp/utils/output.py
leapp/utils/report.py

That is an ugly hack to make leapp preupgrade produce
a json report alongwith default text one.
Json report will be present in the same directory as the
text report.

Introduce json report generation

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

Leapp
* Fixes
- Fix Undefined Model "ReportReference"

Release 0.8.1

---

docs/source/unit-testing.md

tutorial explains that tests shouldn't modify system,
how to prepare environment and how to run tests for actors and libs

update tutorial on writing and running tests

---

leapp/libraries/stdlib/call.py
leapp/reporting/__init__.py
leapp/utils/audit/__init__.py

i.e. make sure that we can pass `unicode` in Py2 context

Handle string types in compatible way

---

leapp/utils/report.py

Add fields to the report:
- Timestamp
- Hostname
- Actor
- Execution context
- Unique ID of the message

Add additional metadata to reporting messages

---

docs/source/devenv-install.md

Related: https://github.com/oamg/leapp-repository/issues/124

Add Leapp Copr repo for Fedora to docs

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

- Add the /var/log/leapp directory to the leapp RPM
- Handle string types in compatible way
- Allow testing actors (run unit & component tests) with workflow config models
- Stop adding 'process-end' audit entry (#538)
- Introduce report composability, remove renders (#543)
- Introduce answerfile generation & usage
- Add additional metadata (hash) to reporting messages to be able to identify them uniquely
- Various fixes in desplaying of generated reports
- Show help message for proper subcommand
- Introduce report composability, remove renders (#543)
- Introduce answerfile generation & usage
- Fix processing of actors when two actors start with the same name (#548)
- Add sanity-check command
- improve failed command error message
- log external command errors to audit

Release 0.9.0

---

docs/source/debugging.md

Added information about minimalist vim/rpdb/nc debugging

docs: update and refactor debugging section

---

packaging/leapp.spec

This is needed after commit 36354ac refactoring.
- also remove Jinja2 as it is not needed anymore

Add python-requests as dependency

---

docs/source/actor-rhel7-to-rhel8.md

Require Title to be generic for reports of the same
semantics.
Also some minor refactor of reporting section has been
done.

docs: reporting.Title best practices

---

leapp/actors/__init__.py
leapp/cli/upgrade/__init__.py
leapp/messaging/__init__.py
leapp/messaging/answerstore.py
leapp/workflows/__init__.py

Previously answerfile was generated from all the dialogs
present in the actors of the workflow, regardless of
whether this or that dialog has actually been shown.
This change collects dialogs actually shown to the user
and populates answerfile accordingly.

Introduce workflow.dialogs

---

docs/source/actor-rhel7-to-rhel8.md
docs/source/dialogs.md

actor-rhel7-to-rhel8.md was updated to contain information
about dialogs and their usage restrictons.

docs: Add some notes about dialogs

---

leapp/models/__init__.py
leapp/models/fields/__init__.py
leapp/repository/__init__.py
leapp/repository/actor_definition.py
leapp/repository/manager.py
leapp/snactor/commands/discover.py
leapp/tags/__init__.py
leapp/topics/__init__.py
leapp/utils/audit/__init__.py
leapp/workflows/__init__.py
leapp/workflows/phases.py
tests/scripts/test_audit.py
tests/scripts/test_repository.py
tests/scripts/test_repository_actor_definition.py

Previously the serialization feature wasn't fully functionally implemented.
This PR is fixing up the missing parts.
The code has been tested in conjunction with the dashboard development.

Fixed json export capabilities using serialization

---

docs/source/actor-rhel7-to-rhel8.md
docs/source/architecture.md
docs/source/best-practices.md
docs/source/conf.py
docs/source/create-repository.md
docs/source/dependencies-leapp-repository.md
docs/source/dependencies.md
docs/source/devenv-install.md
docs/source/faq.md
docs/source/index.rst
docs/source/inhibit-rhel7-to-rhel8.md
docs/source/inplace-upgrade-workflow.md
docs/source/pydoc/leapp.messaging.rst
docs/source/pydoc/leapp.models.rst
docs/source/pydoc/leapp.repository.rst
docs/source/pydoc/leapp.workflows.rst
docs/source/repo-linking.md
docs/source/test-actors.md
docs/source/unit-testing.md
leapp/dialogs/components.py
leapp/messaging/__init__.py
leapp/repository/__init__.py
leapp/repository/manager.py

- fix broken cross-links: https://github.com/oamg/leapp-repository/issues/445
- remove docs for removed leapp modules
- add missing leapp.models.error_severity docs
- ignore missing (generated) module leapp.utils.schemas
- remove the use of depracated 'enable_auto_doc_ref' recommonmark feature
- fix other minor things reported by Sphinx as warnings
Resolves: https://github.com/oamg/leapp-repository/issues/445

Fix readthedocs

---

leapp/reporting/__init__.py

- can be used by KDE/GNOME actor instead of UPGRADE:
https://github.com/oamg/leapp-repository/pull/310

Add DESKTOP tag for the leapp report

---

tests/scripts/test_deprecation.py

Add missing test_deprecation.py

---

.gitignore

Very small MR to add leapp.db to gitignore (because we really don't want to have it tracked)

Add leapp.db to gitignore

---

leapp/utils/report.py

Currently, the plaintext output entries are written in the order they were produced in. This makes it easy for an inhibitor to get lost, when it (at least in my opinion) should be at the very top.
This PR adds a simple `importance` function, which acts as a sort key. After inhibitors, entries with a high risk factor appear next. It can easily be added to the JSON report too, though in that one it makes sense to retain order by timestamp.

Sort text report entries by inhibitor status and risk factor

---

leapp/snactor/fixture.py

Fixes #629
- For py36, py38, and py27 impl is different
Unfortunately, no tests were implemented, due to the fact that in order to see the bug you have to make the error raised. If you try to capture the problem via context pytest.raises, then the bug disappearing

Fix problem when traceback for py3 was lost

---

docs/source/deprecation.md

The deprecation process is not clear as people do not understand what to do when they want to deprecate a leapp entity. To help people understand the deprecation process, let's add more text to make it easier to accept the new process..
Note: it's still not complete. it's just draft. I will mark it for review when I finish it. Do not put here any comments here until it's finished. I opened the draft PR just to make it easier to reference it.

Improve deprecation doc

---

docs/source/dialogs.md
docs/source/el7toel8/inhibit-rhel7-to-rhel8.md

Fix some typos in docs.
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

docs: Fix some typos

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

- Remove pytest residuals in spec file
- Update documentation
- Fix conversion of deprecation messages to reports (py3)
- Fix various issues regarding suppressing of deprecation

Release 0.11.1

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

- Fix the version field in the json schema v1.1.0
- Added rerun command for experimental purposes to be able to re-run the last
phase (Tech. preview)
- Fix the call from the leapp stdlib on Python 3.9

Release 0.12.1

---

.github/workflows/tmt-tests.yml

Also add link to the full pipeline log.

Pass pr_number as env var and copr build as an artifact

---

.github/workflows/pr-welcome-msg.yml

For working example see [my test repo](https://github.com/andywaltlova/actions_test_space/pull/14)
(Same [PR in leapp-repository](https://github.com/oamg/leapp-repository/pull/673))

Replace leapp-pr-welcome-msg-bot with GitHub action

---

.github/workflows/pr-welcome-msg.yml
.packit.yaml

Builds are triggered by commits to master branch and by pull requests

Add packit config for Fedora copr builds

---

docs/source/_static/images/inplace-upgrade-workflow.svg

The IPU Workflow has been updated loooong time ago. Let's reflect
the change as we can call it quite stable really.

Doc: Update the IPU Workflow Image

---

leapp/messaging/answerstore.py

This patch will forbid having values violating `key = value` format in *answerfile* and *answerfile.userchoices*.
If any of those files has invalid value - leapp will fail early informing the user about the location of the problematic option.
OAMG-5861

Check answerfile upon loading

---

.github/workflows/tmt-tests.yml

Looks like phracek's github action is mature enough
https://github.com/sclorg/testing-farm-as-github-action
OAMG-6493

Switch to the official composite action for tft

---

.github/workflows/tmt-tests.yml

Those tests will be scheduled as part of /rerun tests.
OAMG-6980

Run e2e tests on RHEL-8.6-rhui

---

.github/workflows/pr-welcome-msg.yml
.github/workflows/reuse-copr-build.yml
.github/workflows/reuse-tests-7to8.yml
.github/workflows/reuse-tests-8to9.yml
.github/workflows/tmt-tests.yml

Tune tmt tests regexes to align with QE automation
In order for upstream tests and those launched with QE tooling to produce the comparable set of results it's a wise thing to do.

Tune tmt test filters

---

.github/workflows/tmt-tests.yml

Morf tests are gone, meet the new max-sst test.

Update tmt-tests regexes

---

.github/workflows/reuse-copr-build.yml

Add a repo update step to mitigate recent failures.

Tune copr-build action

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

-  Change permissions for /var/lib/leapp to 0700 (#807)
- Prevent unicode errors when printing error messages (#806)
- Make checks for missing answers more strict (#797)
- Expose tracebacks from actors (#802)

Release 0.15.1

---

.github/workflows/tmt-tests.yml

- 8.7->9.0 substituted with 8.8->9.0
- removed unnecessary TARGET_KERNEL env var

Update upgrade paths and env vars in tests

---

docs/source/_static/images/inplace-upgrade-workflow.svg
docs/source/terminology.md

@pirat89, doc terminology fixes we talked about. Thanks!

terminology fixes

---

docs/source/_static/images/inplace-upgrade-workflow.svg
docs/source/best-practices.md
docs/source/compatibility-with-leapp-repository.md
docs/source/dependencies.md
docs/source/deprecation.md
docs/source/el7toel8/actor-rhel7-to-rhel8.md
docs/source/el7toel8/deprecation.md
docs/source/unit-testing.md
docs/source/workflow-apis.md

Fixing some spelling errors codespell turned up. 
review please @oamg/developers

fix spelling errors in docs

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

- Generated txt report file now contains also External links when part of a report (#842, #844)
- The `run` function is now compatible with Python 3.12 (#845)

Release 0.17.0

---

leapp/__init__.py
man/leapp.1
man/snactor.1
packaging/leapp.spec

- Start building for EL 9 in the upstream repository on COPR (#855)
- Minor update in the summary overview to highlight what is present in the pre-upgrade report (#858)
- Store metadata about actors, workflows, and dialogs inside leapp audit db (#847, #867)
- Implement singleton leapp execution to prevent multiple running leapp instances on the system in the same time (#851)
- Close properly all file descriptors when executing shell commands via `run` (#880)
- Code is now Python3.12 compatible (#855)

Release 0.18.0

---

leapp/utils/audit/__init__.py

When directory is missing, this change will introduce creation of missing path and allow proceeding with execution.
JIRA: RHEL-54382

Handle case when db directory is missing

---

Makefile
res/container-builds/Containerfile.fedora_generic

* Add installation of python3-setuptools
* Drop fedora versions 35-40
Jira: RHELMISC-13271

Update build container up to f42
