cockpit/leapp.html, leapp-tool.py, leappto/providers/libvirt_provider.py
Also switches the Cockpit plugin over to using the new option,
so the list refreshes in ~3 seconds rather than ~10.
=> Issue #5: add `--shallow` option to `list-machines`

.gitignore, Pipfile, Pipfile.lock, README.md, integration-tests/.gitignore, integration-tests/Pipfile, integration-tests/Pipfile.lock, integration-tests/README.md, integration-tests/features/environment.py, integration-tests/features/httpd-stateless.feature, integration-tests/features/steps/common.py, integration-tests/vmdefs/centos6-guest-httpd/Vagrantfile, integration-tests/vmdefs/centos6-guest-httpd/ansible/playbook.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/defaults/main.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/handlers/main.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/tasks/configure.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/tasks/install.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/tasks/main.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/tasks/secure.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/httpd/templates/default.tpl, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/init/handlers/main.yml, integration-tests/vmdefs/centos6-guest-httpd/ansible/roles/init/tasks/main.yml, integration-tests/vmdefs/centos7-target/Vagrantfile, integration-tests/vmdefs/centos7-target/ansible/playbook.yml, integration-tests/vmdefs/centos7-target/ansible/roles/docker/tasks/main.yml, integration-tests/vmdefs/centos7-target/ansible/roles/init/tasks/main.yml, leapp-tool.py, start_integration_vms.sh
- expected behaviours defined with behave and PyHamcrest
- configures local VMs with Vagrant and Ansible
- uses Leapp to run macrocontainer redeployments
and query local IP addreses
- uses requests to check web service behaviour
- uses pipenv to manage the test environment itself
Known issues:
* VM IP addresses are not being retrieved correctly
* relies on the SSH kludge in leapp-tool to access the VMs
* even the simple baseline scenario takes ~5 minutes to run (~200s for VM setup, ~100s for the migration)
=> Initial integration testing environment

Pipfile, Pipfile.lock, integration-tests/README.md, integration-tests/features/environment.py, integration-tests/features/steps/common.py
This PR migrates the test helpers from functions in the `common` steps file to helper objects passed to step implementations as attributes on the scenario context.
=> Move test helpers to behave context

ansible_roles/httpd/defaults/main.yml, ansible_roles/httpd/handlers/main.yml, ansible_roles/httpd/tasks/main.yml, ansible_roles/httpd/templates/default.tpl, ansible_roles/target/tasks/main.yml, demo/vmdefs/centos7-target/playbook.yml, integration-tests/vmdefs/centos7-target/ansible/playbook.yml
Currently we only need to create a `/opt/leapp-to` directory
=> Add `target` role responsible for setting up the target env

integration-tests/features/environment.py
The autoskipping logic for scenarios tagged with `@skip` wasn't
quite right, this fixes it.
=> Correctly skip tagged scenarios

integration-tests/features/environment.py, integration-tests/features/steps/common.py
The Ansible playbooks for the test VMs are now always run for each
VM provisioning step, providing the following benefits:
- playbook changes will automatically be picked up on the next test
run, even when re-using previously created VMs
- playbooks can ensure VMs are reverted to a known state prior to
use, without having to completely destroy and recreate the VM
- VMs can now readily be reprovisioned within a test scenario
=> Issue #28: always reprovision test VMs

demo/vmdefs/centos6-guest/Vagrantfile, demo/vmdefs/centos7-target/Vagrantfile, start_vms.sh
I have often the problem of being in a 10.0.0.0 network. I then can not run the demo, vagrant complains that: `Error while activating network: Call to virNetworkCreate failed: internal error: Network is already in use by interface enp0s31f6.`
This patch allows one to customize the addresses of the source and target VMs using environment variables SRCIPADDR and DSTIPADDR. Care was taken to keep the defaults in case the variables are unset or null.
Should be probably also done for:
- start_integration_vms.sh and vagrantfiles under integration-tests/vmdefs
- centos7-guest (@shaded-enmity, now it gets 10.0.0.11, isn't it a typo? I would suppose the source VM should get 10.0.0.10.)
=> Make the IP addresses of the demo VMs configurable

integration-tests/features/list-machines.feature
We're postponing any work on status caching until
we know more about what the actual deployment architecture
that supports introspection and conversion of remote VMs
is going to look like (as opposed to the current
local VM focused prototype)
=> Drop WIP status caching test

centos-ci/jobs/integration_test.yml
This should also fix the brace-escaping issue that is currently going on in CentOS CI
=> Move the scm block to its own section

README.md
- without a "--tcp-port 9000:9000" argument to leapp-tool the target VM will not show the PHP admin page
- document that the PHP admin page is on port 9000, this is not obvious.
=> Add TCP port details to the demo instructions.

demo/vmdefs/centos6-drools-guest/Vagrantfile
The previous setting of '10.0.0.10' was clashing with the
definition of centos6-guest IP
=> Fix default IP in the drools Vagrant file

demo/vmdefs/centos6-drools-guest/Vagrantfile, demo/vmdefs/centos6-guest/Vagrantfile, demo/vmdefs/centos7-target/Vagrantfile, integration-tests/vmdefs/centos6-guest-httpd/Vagrantfile, integration-tests/vmdefs/centos7-target/Vagrantfile, src/leappto/providers/libvirt_provider.py
This PR reenables --no-application and --no-icon usage when available in virt-inspector and adds only channels in vagrant images when they are available.
=> Re-enable the --no-applications usage of virt-inspector

integration-tests/features/environment.py, src/leappto/cli.py, src/leappto/providers/libvirt_provider.py
Most leapp-tool operations should be executable
without local root privileges, so drop the
requirement to always run it as root.
Instead, "sudo" is used for the commands that
need to be run as root for interoperability
with the Vagrant based tests and demo plugin.
=> Allow leapp-tool to be run as non-root user

cockpit/leapp.html, leapp.spec
This is a Fix for the problem introduced in #102
=> Leaving the documented tool path in cockpit and fix it during rpm creation for RPM installations

integration-tests/README.md, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/remote-authentication.feature, integration-tests/features/steps/remote_authentication.py, src/leappto/cli.py
When no --identity file is specified, the CLI now falls back
on the default SSH credentials (typically provided by ssh-agent)
Closes #103
=> #103: Allow use of default SSH credentials in CLI

ansible_roles/sshd-password-auth/handlers/main.yml, ansible_roles/sshd-password-auth/tasks/main.yml, centos-ci/bootstrap.sh, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/remote-authentication.feature, integration-tests/features/steps/destroy_containers.py, integration-tests/features/steps/remote_authentication.py, integration-tests/vmdefs/centos7-target/ansible/playbook.yml, leapp.spec, src/leappto/cli.py
This uses getpass.getpass() to interactively retrieve a password
from an interactive prompt, and then sshpass to pass it along
to ssh via a custom file descriptor.
The associated test case similarly uses sshpass to supply the
test password to the LeApp CLI.
To avoid problems with the default per-tty credential caching
in sudo, the test case only runs when the tests are being
run as root (as is the case in CI).
=> Support --ask-pass option in CLI

Pipfile, centos-ci/ansible/playbook.yml, centos-ci/ansible/roles/cockpit-integration/tasks/main.yml, centos-ci/bootstrap.sh, integration-tests/features/cockpit-demo.feature, integration-tests/features/steps/cockpit_demo.py
To help avoid further regressions along the lines of #122, this enables
execution of the Cockpit plugin integration tests during CI
=> Enable Cockpit plugin integration testing

docs/source/integration-tests.rst, integration-tests/features/cockpit-demo.feature, integration-tests/features/environment.py, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/steps/common.py
Due to recent changes in the way source & target VM lookup
is handled, the Cockpit plugin integration test now requires
that the VMs it uses be started by the root user (otherwise
it fails to find them).
While this isn't a problem for CI (where the tests run as
root), it causes problems when running the tests as a
normal user in a local `pipenv shell` session.
To fix that, the follow changes have been made:
- test scenarios can now indicate they need their VMs
started as root, and if the tests are running as a
normal user, the VMs will be destroyed and recreated
by root
- test scenarios can now be marked with `@root_recommended`
to indicate that they're really slow or otherwise
problematic when run as a non-root user
- the Cockpit plugin integration test has been updated to
use both of …
=> Restore ability to run tests as non-root user

centos-ci/bootstrap.sh
Some of Ansible's dependencies now use `cffi`, and hence require that
the `libffi` headers be available on the system when installed via `pip`.
Rather than ensuring that is the case directly, we instead install Ansible
from EPEL rather than PyPI.
=> Use EPEL Ansible package & dependencies

.gitignore, Pipfile, Pipfile.lock, docs/source/contributing.rst, docs/source/integration-tests.rst, integration-tests/features/default-port-detection.feature, integration-tests/features/httpd-stateless.feature, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/steps/common.py
This attempts to speed up the test suite again be removing the
current usage of the "ensure fresh" option when setting up the
test VMs.
It also updates the integration test development and code
review documentation accordingly.
Fixes #166 and #165
=> Avoid setting "ensure fresh" in the integration tests

src/leappto/cli.py, src/leappto/driver/ssh.py
- Display error message in case of a SSH Connection exception is raised;
- Check if target machine is accessible;
- Do not  show traceback in case of a SSH Connection exception.
=> Change output if Source/Target machine is not accessible via SSH

integration-tests/features/default-port-detection.feature, integration-tests/features/environment.py, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/port-inspect.feature, integration-tests/features/steps/default-port-detection.py, integration-tests/features/steps/port_inspect.py
- ClientHelper ensures commands that need sudo are
always run with sudo
- IP addresses are no longer hard coded in test cases
- relaxed some of the timing requirements for test steps
- fixed some typos and awkward phrasing in step definitions
Fixes #165
=> Tidy up port scanning in the test suite

integration-tests/features/check-target.feature, integration-tests/features/httpd-stateless.feature, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/steps/check_target.py, integration-tests/features/steps/common.py, integration-tests/features/steps/remote_authentication.py, src/leappto/cli.py
- reports names already claimed on target system
- implicitly checks for privileged access to target
Additional changes:
- auth integration tests now use check-target
- new test setup step to claim names on target systems
- new test step to rerun the previous migration command
=> check-target subcommand

src/leappto/cli.py
Based on a TODO comment present on source code, this PR proposes:
- Instead of creating a container and a macro container directory with name "container" use "container_<source_hostname>" to make it easier to know from which machine such container was created;
- Enable user to define a specific container name during migration using --container-name or -n options.
=> [Proposal] Derive container name from source hostname

integration-tests/features/httpd-stateless.feature, integration-tests/features/leapp_testing/__init__.py, src/leappto/cli.py
- migrate-machine port remapping moved into MigrationContext
- target access checked before calculating port mapping
- port mapping helpers moved to CLI module top level
- related test steps enabled
=> Check target access early in migrate-machine

src/leappto/cli.py
When executing check-target for localhost  (127.0.0.1) an exception occurred:
```
$ sudo bin/leapp-tool check-target 127.0.0.1
container
dreamy_lamarr
vibrant_stonebraker
RC: 0 Containers: None
Traceback (most recent call last):
File "bin/leapp-tool.real", line 11, in <module>
load_entry_point('leappto==0.0.1', 'console_scripts', 'leapp-tool')()
File "/home/vfeenstr/.local/venvs/leappto/lib/python2.7/site-packages/leappto/cli.py", line 778, in main
return_code, claimed_names = mc.check_target()
File "/home/vfeenstr/.local/venvs/leappto/lib/python2.7/site-packages/leappto/cli.py", line 589, in check_target
names = containers.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
This PR solves this issue
=> cli: Fix check-target exception for localhost

src/leappto/providers/ssh.py
An unqualified "python" may end up running either Python 2
or Python 3, depending on whether or not a virtual
environments or Software Collection is active.
Using Py3-style print syntax allows command snippets to work
in either, but some imports (e.g. rpm) may still require
access to the system or SCL site-packages directory.
=> Handle running in a Py3 virtual environment

src/leappto/cli.py
While listing containers on target machine do not fail if missing macro containers storage dir, as seem on #190
=> Check-target do not fail if storage dir is missing on target machine

centos-ci/jobs/integration_test.yml
this would allow upto 4 runs of the job to execute in parallel, they would run from their own workspace and run on their own worker nodes, so should not impact each other.
the only place where this might cause an issue is when there is state or some config maintained outside the specific workspace. it might be good to watch closely the first few runs.
=> enable concurrent runs

integration-tests/features/destroy-containers.feature, integration-tests/features/httpd-stateless.feature, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/steps/check_target.py, integration-tests/features/steps/common.py, integration-tests/features/steps/destroy_containers.py, src/leappto/cli.py
- adds `migrate-machine --force-create`
- replaces `destroy-containers` with `destroy-container <name>`
Also updates the integration tests and integrating testing
infrastructure accordingly.
=> Selective container removal and forced creation

cockpit/leapp.html
Until this has not been implemented this won't do anything except causing the CLI call to fail when checked due to an unknown parameter
=> ui: Add force create checkbox

cockpit/leapp.html
The default mapping will cause, that port found by default mapping will be added although the checkbox is not checked. Therefore, an parameter was added into the command executed from UI to disable this behavior.
=> Disabled default port mapping for migration executed from UI

src/leappto/cli.py
commit: d5109fb
I found out that we have fundamental error in port mapping where mapping of same source port to multiple destination port didn't work properly. 
commit: c62d17b
While I was in the middle of the work I realized that someone moved the port mapping partially while the _port_remap function was defined outside of the MigrationContext, but used from it. Therefore I decided to move _port_remap function into MigrationContext as well as a method of it (for now).
=> Missing port mapping

src/leappto/cli.py
and actually there has been no service named mysqld, only mysql55-mysqld, so
the mysqld part never did anything.
=> Remove the fix_upstart function, turns out that it was not needed

src/leappto/cli.py
I've added --exclude-path option for migrate-machine command. I am not sure, whether we should keep the default list of excluded paths as it was before: 
'/dev/*', '/proc/*', '/sys/*', '/tmp/*', '/run/*', '/mnt/*', '/media/*', '/lost+found/*'
Or rather go this way:
'/dev/*', '/proc/*', '/sys/*', '/tmp/*', '/run/*',  '/lost+found/*'
Because there might be a situation that user will have some service data in /mnt or /media:
P.S. Virt-tar-out exclusion was not implemented since we are planning to drop it anyways.
=> CLI: Added support for exclude paths

leapp.spec
right now leapp won't run on a fresh install, it misses docker during setup and python  libs
=> add missing deps to leapp.spec 

cockpit/leapp.html, docs/source/leapp-tool.rst, integration-tests/features/leapp_testing/__init__.py, integration-tests/features/steps/destroy_containers.py, integration-tests/features/steps/remote_authentication.py, src/leappto/cli.py
Set default target for:
destroy-container
check-target
And unified it with migrate-machine, so the target can be changed using -t option.
=> Set default target for destroy-container and check-target

ansible_roles/docker/tasks/main.yml, integration-tests/features/httpd-stateless.feature, integration-tests/vmdefs/centos7-guest-httpd/Vagrantfile, integration-tests/vmdefs/centos7-guest-httpd/ansible.cfg, integration-tests/vmdefs/centos7-guest-httpd/ansible/playbook.yml, src/README.rst, src/leappto/cli.py
Image is now based on centos/systemd in order to save some work with removing *.wanted folders content. 
To be able to run it, the container_manage_cgroup selinux boolean has to be enabled (P.S. even for upstart based distros, if we want to access cgroups)
"--cap-add", "SYS_ADMIN" parameter also added since this will be required on docker 1.13 (tested), but it works without it on current fedora docker 1.12
=> Enable systemd based source machine migration

src/leappto/cli.py
Currently `docker stop` sends SIGTERM and then simply kills everything, as Upstart does not react to SIGTERM. This caused fsck to be run (before that was fixed in other PRs) and probably is not ideal for various other reasons (e.g. databases might prefer to be shutdown properly instead of being just killed).
Fix this by letting Docker send SIGINT to Upstart to let it shutdown the services properly. Upstart interprets SIGINT as Ctrl-Alt-Del and runs the shutdown scripts.
To verify that it works properly for the demo case: run `docker stop` and check that  /var/lib/leapp/macrocontainers/container_centos6-app-vm/var/log/mysql55-mysqld.log contains
`[Note] /opt/rh/mysql55/root/usr/libexec/mysqld: Shutdown complete`
and /var/lib/leapp/macrocontainers/container_centos6-app-vm/var/log/httpd/error …
=> Proper shutdown procedure for Upstart macrocontainers

centos-ci/bootstrap.sh
Hardcoding epel version will work only temporarily. Idea from:
https://github.com/geerlingguy/ansible-role-repo-epel/blob/master/defaults/main.yml
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>
=> centos-ci/bootstrap.sh: fix epel release url

Pipfile
I discovered this issue while I was testing the docker images. Basically what is going on here is that we require selenium version < 3.0, but we do not limit the dependencies of selenium. The result was that the dependency tree could not be solved.
=> MOD: Splinter version fix to <0.7.6

Makefile
Added makefile which contains so far just dummy targets. This is needed in order to unify build process of every single core repository.
=> Added makefile with dummy targets

docs/Makefile, docs/source/index.rst, requirements-docs.txt
[Sphinx-autobuild](https://github.com/GaretJax/sphinx-autobuild) - Watch a Sphinx directory and rebuild the documentation when a change is detected. Also includes a livereload enabled web server.
Usage to run the server on localhost:
`$ make livehtml`
=> Add support for sphinx-autobuild

docs/source/first-actor.md
The anchor points to wrong url:
https://leapp.readthedocs.io/en/latest/terminlogy.html#phase
"terminlogy" instead of "terminology"
=> Doc - Fix "Phase" terminology anchor in first-actor.md

docs/source/working-with-workflows.md
Issuing "snactor workflow run Example" from working-with-workflows.md doc fails with:
```(venv) [mreznik@localhost tutorial-linked]$ snactor workflow run Example
2018-10-04 17:41:37.889 INFO     PID: 26918 leapp: Logging has been initialized
2018-10-04 17:41:37.918 INFO     PID: 26918 leapp.repository.tutorial-linked: A new repository 'tutorial-linked' is initialized at /home/mreznik/work/upstream/leapp/tutorial-linked
2018-10-04 17:41:37.939 INFO     PID: 26918 leapp.repository.tutorial: A new repository 'tutorial' is initialized at /home/mreznik/work/upstream/leapp/tutorial
Traceback (most recent call last):
File "/home/mreznik/work/upstream/leapp/venv/bin/snactor", line 11, in <module>
sys.exit(main())
File "/home/mreznik/work/upstream/leapp/venv/lib/python2.7/site-packages/leapp/snacto …
```
=> Doc - remove "filters" import statement as it does not exist

leapp.spec, man/leapp.1, man/snactor.1
Manpages are generated by help2man tool by a Makefile target `manpages`.
What is missing are inculde files (`man/{leapp,snactor}.h2m`) to be used by help2man tools to make the output look less stubble.
=> Add manpages for leapp and snactor executables

leapp/models/__init__.py
It happens that sometimes there is a typo in a field name and the field is then ignored by the framework while originally intended field is created with missing() as default if not required.
=> Add undefined model field check

leapp/models/__init__.py, tests/scripts/test_models.py
Previously when inheriting from a Model, fields from the base class weren't taken into account.
This PR fixes this mistake by copying the fields from the base class
=> Fix inheritance of Models

docs/source/debugging.md, leapp/cli/__init__.py, leapp/logger/__init__.py, leapp/snactor/__init__.py
tl;dr;
- Do not override the LEAPP_DEBUG value when the --debug option is
not used and LEAPP_DEBUG is already set.
- Set a logging level to DEBUG only when LEAPP_DEBUG == 1, otherwise
use the INFO level.
Previously, the LEAPP tool ignored LEAPP_DEBUG set from the
commandline completely. So the value has been set only based on
use of the --debug option. Additionaly, the logging level has been
set to DEBUG in case the LEAPP_DEBUG has not been set.
=> Set & use the LEAPP_DEBUG env properly

leapp/cli/upgrade/__init__.py, leapp/dialogs/__init__.py, leapp/dialogs/dialog.py, leapp/workflows/__init__.py, leapp/workflows/flags.py
Previously reboots were always executed automatically, however this
behaviour isn't always wanted. Users and testers might need to do
things before the actual reboot.
This patch introduces a --reboot flag to the leapp upgrade
command line tool which will instruct the framework to perform
the reboot when it is requested. When the flag is not present
the upgrade will not performed and just a message will be presented
to the user asking them to reboot.
=> upgrade: Auto reboot functionality

leapp/snactor/commands/discover.py, leapp/snactor/utils.py
only static analysis to prevent runtime errors from influencing the process.
Fixes #338
=> Introduce alternative `safe` variant of `snactor discover` using

leapp/models/fields/__init__.py
Previously the Model field type, did not check whether or not it
received a reference as model to use, which resulted in some validation
error if the real model was passed to it. This PR fixes this problem
by trying to get the _resolved field from the model and defaults
to the actual model type that has been passed.
Fixes https://github.com/leapp-to/leapp/issues/374
Related-issue: https://github.com/leapp-to/leapp/issues/374
=> models: Support model references in fields.Model

leapp/repository/actor_definition.py
When executing leapp in a debugger it can happen that stdin can not
be opened with fdopen, in this case an OSError can occur. This patch
handles that scenario, but will imply that stdin might not be working
as expected in some cases. We won't be able to handle those cases but
this only happens within a debugger at this point. Therefore this
patch is good enough for now.
=> actordefinition: Make stdin opening more robust

leapp/cli/upgrade/__init__.py, leapp/snactor/commands/run.py, leapp/snactor/commands/workflow/run.py, leapp/utils/output.py
At the moment when an actor fails, two tracebacks are
thrown to the stderr. One for an actual failure in the actor
and the other (the last one) about the actor failure itself.
As the last traceback is not useful at all we shall keep only
the first one.
=> Avoid showing multiple tracebacks to users

Makefile
Previously, in case that between two calls of commands, where
the $(TIMESTAMP) have been included, have been processed in different
TIME (HH:MM), both commands result with different $(TIMESTAMP).
We want to proceed the make process with one persistant $(TIMESTAMP)
so we will avoid random errors related to the change of time. E.g.:
cannot find prepared SRPM, because TIMESTAMP is different.
Problem is resolved in way that TIMESTAMP can be defined on the
cmdline. But to do not require it, special *_remake* target has been
added, which will call the make again with the TIMESTAMP value
in case the TIMESTAMP was not set.
Reproducer:
1. Prepare Makefile like this:
```
TIMESTAMP=`date +%Y%m%d%H%MZ -u`
wait:
@echo $(TIMESTAMP)
@./wait_script.sh
@echo $(TIMESTAMP)
```  
2. call `make`
=> Packaging: persistent TIMESTAMP

docs/source/best-practises.md, docs/source/index.rst, docs/source/repository-dir-layout.md
- the rest of the best practices will move to https://github.com/oamg/leapp-repository/tree/master/docs
=> Move repo dir layout to a separate page

docs/source/messaging.md, leapp/models/__init__.py, leapp/models/fields/__init__.py, tests/scripts/test_models.py, tests/scripts/test_serialization.py
Currently we are using "missing" function as a placeholder
in cases where no value was specified in the particular field.
This might be confusing and can introduce issues when not
understood correctly. This patch is removing concept of the
missing function together with "allow_null" and "required"
parameters and switch to using a new nullable field type.
In this case every field which is not nullable has to be
specified. If we want to allow a field to be None we need to
wrap it around the nullable field.
E.g. fields.nullable(fields.String())
=> Introduce nullable field type

leapp/actors/__init__.py, leapp/cli/__main__.py, leapp/compat.py, leapp/repository/actor_definition.py, leapp/repository/scan.py, leapp/snactor/__init__.py, leapp/snactor/utils.py, leapp/utils/i18n.py
This commit introduces the initial changes necessary for allowing,
our code and actors to be localizable with gettext.
Magic builtins `_()` and `P_()` have been introduced with inspiration
taken from the DNF implementation to solve this.
Usage examples:
* Localization without need of pluralization:
```
localized_string = _('localized')
```
* Localization with the need of pluralization:
```
localized_string = P_('%d item', '%d items', 2)
```
=> Initial localization support

leapp/libraries/stdlib/call.py, tests/scripts/test_stdlib_call.py
This function provides stable interface across Python2 and Python3.
Besides, the main difference between this and the various `subprocess`
related functions is that we can easily "tee" the output to stdout/stderr
while buffering it internally for auditing.
Note that the `_call` function should provide internal interface for Leapp and that we should provide additional "facade" on top of that function to simplify the interface (and perhaps mimic the `subprocess` interface).
You can easily test this function by calling the file directly:
```
$ python2 call.py bash -c 'echo 123 ; (>&2 echo err) ; exit 255'
123
err
{'exit_code': 255,
'pid': 16412,
'signal': 0,
'stderr': u'err\n',
'stdout': u'123\n'}
$ python3 call.py dnf update
Error: This command has to be run under the root user. …
```
=> Introduce a way of running external programs

leapp/actors/__init__.py, leapp/libraries/stdlib/api.py, leapp/snactor/fixture.py, tests/data/actor-api-tests/.leapp/info, tests/data/actor-api-tests/.leapp/leapp.conf, tests/data/actor-api-tests/actors/first/actor.py, tests/data/actor-api-tests/actors/first/files/duplicate, tests/data/actor-api-tests/actors/second/actor.py, tests/data/actor-api-tests/actors/second/files/duplicate, tests/data/actor-api-tests/files/duplicate, tests/data/actor-api-tests/models/apitest.py, tests/data/actor-api-tests/tags/actorfileapi.py, tests/data/actor-api-tests/topics/apitest.py, tests/scripts/test_actor_api.py
This patch introduces the actor convenience api for actors and
repository libraries and provides an easy access to the functions that
actors have access to.
Such as:
- Producing messages
- Consuming messages
- Retrieving files or directory paths
- files that are bundled with the actor itself
- shared files on repository level
- Access to the currently running actor instance
- Access to the logger of the currently running actor instance
- Reporting errors
=> stdlib: Actor API convenience library

packaging/leapp.spec
Add metapackage for dependencies
Currently we are not able to use python dependencies correctly to
ensure the RPM will not be removed during the upgrade of the system.
As a workround, put all such system dependencies into the leapp-deps
metapackage.
This metapackage is supposed to be built for the same system where
leapp should be installed. When different dependencies are needed
on target system (e.g. during the in-place upgrade) repository is
reponsible to deliver new meta package with such dependencies.
Leapp framework from this point will require specific capability:
leapp-framework-dependencies
which has to be provided by such meta package. Any time the
dependencies are changed, the capability number has to be incremented
by one. So packages provided by leapp repository has to …
=> Add metapackage for dependencies

docs/source/pydoc/leapp.libraries.stdlib.rst
=> docs: Include leapp.libraries.stdlib.api in the python documentation

leapp/libraries/stdlib/__init__.py
Since I have been seeing some breaking usage of the api module by trying to import stdlib and using stdlib.api I added it as an import in the module to allow this.
After this change one can write this:
```python
from leapp.libraries import stdlib
stdlib.api.report_error(....)
```
Previously it was necessary to it like this:
```python
from leapp.libraries.stdlib import api
api.report_error(...)
```
Otherwise the api module wouldn't have been available.
=> stdlib: Make api directly available in stdlib

leapp/repository/scan.py, tests/scripts/test_repository.py
If any snactor command is run before repos are
registered with snactor repo find command a
not much helping KeyError appears in error log,
because it isn't assumed that user repos may not
be configured at that point.
This patch addresses the issue by checking user repos
data presence and in case any missing links are found
raising RepositoryConfigurationError with a relevant
error message.
Closes-Issue: #357
=> snactor: fix cryptic message without user repo config

leapp/repository/__init__.py, tests/scripts/test_snactor.py
After registering several different objects
with the same name (ex. actor and tag),
snactor discover without --safe would return
wrong path for actual files for all objects
but the one registered last.
This fix addresses the issue by utilizing
the fact that repo structure remains the same
and adding object type check in _get_class_file
path resolution.
Closes-Issue: #431
=> snactor discover: fix wrong path

leapp/actors/__init__.py
- description attribute of the Actor class is deprecated now
- added missing docstring for the return value of consume() method
=> Update Actor class description and consume() docstring

leapp/actors/__init__.py
Recently we spent some time with debugging "issue" with missing a model in produces tuple with @jmikovic and @shaded-enmity. This should help to save some time of actor developers.
Am I missing anything in this fix @vinzenz ? It does not have to be "AssertionError" of course.
=> Print a warning msg when missing model in "produces" tuple

leapp/snactor/commands/new_topic.py, tests/scripts/test_snactor.py
If a topic creation is attempted outside leapp repository
directory it will fail with a trace during os.path.join.
This fixes the issue by validating that command execution
takes place in the actual leapp repo directory.
Closes-Issue:#456
=> snactor: fixed trace on topic creation

leapp/snactor/commands/workflow/run.py, leapp/snactor/context.py, leapp/utils/audit/__init__.py, tests/scripts/test_snactor.py
This implements a new feature for the `snactor workflow run` command,
that allows to store all messages from snactor workflow run to be
available for consumption by actor executed through `snactor run`.
Usage scenario:
---------------
One wants to write an actor that needs to consume from the
FactsCollection phase of the IPU workflow.
Before we introduced this parameter, one had to manually run every
actor, that is required to produce the messages the actor needs to
consume, manually with the --save-output parameter.
With the new feature one can now run:
$ snactor workflow run --save-output --until-phase FactsCollection ipu
And then can normally use `snactor run` to start testing the actor.
$ snactor run MyNewActor --print-output
=> snactor: Workflow run --save-output

leapp/models/fields/__init__.py, tests/scripts/test_serialization.py
The JSON field type, is a fields that allows to assign any value that is
encodable to JSON by the json library of the python standard library.
With the exception for None value as the value itself. This is to keep
consistency with the rest of the fields, that require the field to be
marked as nullable. None value nested within, however is not restricted
by this limitation.
Example usage:
```python
class JsonUsedModel(Model):
topic = SomeTopic
data = fields.JSON()
nullable_data = fields.Nullable(fields.JSON())
m = JsonUsedModel()
m.data = {'valid': None} # valid value
m.data = None # invalid value for this field
m.nullable_data = None # valid
m.nullable_data = {'valid': None} # valid value
```
=> model.fields: Introduction of the JSON field type

docs/source/dependencies.md
This document aims to inform how to proceed when is necessary to add new dependencies to the framework.
=> Documentation for metapackages dependencies

leapp/libraries/stdlib/config.py, tests/scripts/test_stdlib.py
Previously environment variables for debug and verbose mode had to be
manually checked by doing comparison to a string.
For example:
```python
if os.getenv('LEAPP_DEBUG', '0') == '1':
do_something_debuggy()
if os.getenv('LEAPP_VERBOSE', '0') ==  '1':
do_something_verbose()
```
This has been a constant source of mistakes, by forgetting to put the
numbers in quotes. In addition to this, it is very verbose and not very
convenient. Thus this change introduces two new functions in the
standard library that can be used to check those variables.
is_debug() will return True if LEAPP_DEBUG has been set to '1'
is_verbose() will return True if either LEAPP_DEBUG or LEAPP_VERBOSE are
set to '1'
=> stdlib: Functions to check the current config

leapp/cli/upgrade/__init__.py
Previously, when starting leapp with debug or verbose, applied to
commandline and environment variable enablement, the information was no
longer respected after resuming.
The problem has been incorrect handling of variables checking. This
patch fixes the problem and moves out the check into a function.
=> leapp: Fix debug/verbose restore on resume

leapp/utils/clicmd.py
Previously, it wasn't possible to write a simple tool, which does not
use subcommands. With this change, it allows to use the clicmd code also
for tools that do not use subcommands.
=> clicmd: Add support for tools without subcommands

leapp/utils/clicmd.py
Previously when calling a command that has subcommand on the commandline
did not give the user any feedback on the usage.
As an example expected usage would be:
$ tool command subcommand
But the user would type:
$ tool command
The tool would silently and successfully exit.
With this change, the tool will now print the help and exit with exit
code 2.
Fixes #455
=> clicmd: Print help if a parent command is called

etc/leapp/logger.conf, leapp/logger/__init__.py
When LEAPP_DEBUG is not 1, self.log.error() and self.log.critical() won't print anything to stderr.
This should be true for lower severities, but from error up, things should appear also on stderr.
=> Change default loglevel to ERROR

leapp/actors/__init__.py, leapp/libraries/stdlib/api.py, leapp/repository/__init__.py, leapp/repository/actor_definition.py, tests/data/actor-api-tests/actors/first/tools/directory/exec_script, tests/data/actor-api-tests/actors/first/tools/directory/nonexec_script, tests/data/actor-api-tests/actors/first/tools/first-actor, tests/data/actor-api-tests/actors/second/tools/directory/exec_script, tests/data/actor-api-tests/actors/second/tools/directory/nonexec_script, tests/data/actor-api-tests/actors/second/tools/second-actor, tests/data/actor-api-tests/tools/directory/exec_script, tests/data/actor-api-tests/tools/directory/nonexec_script, tests/data/actor-api-tests/tools/repository, tests/scripts/test_actor_api.py
This change introduces an API for being able to retrieve the location of
executable tools within repo/tools or repo/actors/<actor>/tools
This allows to retrieve the full path to a tool bundled with the
repository or an actor just like we do support this for files.
=> stdlib.api: Add tools files api

leapp/cli/upgrade/__init__.py
Previously, leapp upgrade would have return error code `0` even when
errors have been reported through the framework.
This change introduces the reporting of exit code `1` in case errors
have been reported.
Fixes #371 
Fixes #397
=> leapp upgrade: Fail with exit code 1 after errors

leapp/libraries/stdlib/api.py
`leapp.libraries.stdlib.api.current_logger` currently fails if no actor
is currently running. However this function is used by some other
libraries that, at least in test cases need to do the logging too.
This change introduces a fallback in case current_actor returns None.
=> stdlib.api: Use a fallback logger

docs/source/index.rst
To indicate that it's for developers. At least for now there nothing for users.
=> Update title of the readthedocs

leapp/libraries/stdlib/__init__.py
As in debug mode we have a lot of messages the user needs to be informed which external command has generated certain output.
This PR wants to solve this by adding this output:
```
leapp.workflow.Download.prepare_upgrade_transaction: External command is started: [/usr/bin/dnf rhel-upgrade]
*** external command output ***
leapp.workflow.Download.prepare_upgrade_transaction: External command is finished: [/usr/bin/dnf rhel-upgrade]
```
=> Show information in debug mode about external commands

leapp/libraries/stdlib/__init__.py, tests/scripts/test_stdlib.py
We want to get rid of the subprocess library and we found the call
function as expendable as we want from people to use just `run` for
everything.
=> stdlib: remove the call function

leapp/libraries/stdlib/call.py, tests/scripts/test_stdlib_call.py
We found that we are not able to handle linebuffer correctly now.
Sometimes it happens that the buffered string is broken because it
ends in the middle of utf8 character. This is temporary solution.
=> stdlib: _call: Ignore the linebuffer

leapp/workflows/__init__.py, leapp/workflows/flags.py
We need to stop the execution of the workflow in some cases without
the reboot requirement. Adding the flag to provide such functionality.
=> Workflow: add the is_checkpoint flag

leapp/actors/__init__.py
~~The definition.full_path contains path through symlink, e.g.:
/etc/leapp/repos.d/system_upgrade/...
and entry['path'] contains real path, e.g.:
/usr/share/leapp-repositories/...
Not sure about the hidden idea but this is blocking us and we need to
resolve transition to Python3 asap... so - hacky way. Someone can fix
it properly later~~
EDIT:
Use realpath when load actors?
The definition.full_path contains path through symlink, e.g.:
/usr/share/leapp-repositories/...
and entry['path'] contains real path, e.g.:
/etc/leapp/repos.d/system_upgrade/...
Not sure about the hidden idea but this is blocking us and we need to
resolve transition to Python3 asap... so. Not sure whether there is
special use case for this. Currently all actors in leapp.actors
use realpath.
=> Use realpath when load actors?

leapp/libraries/stdlib/__init__.py, leapp/libraries/stdlib/call.py
Now the __write_raw (and run) function should be working with Py2
and Py3 as well, but it is temporary solution as the leapp.stdlib.call
is still in bad shape.
Fixes: #487
Related issue #488
=> Temporary fix of leapp.stdlib

leapp/messaging/__init__.py
Fix wrong timestamp of reported error.
When inhibitor is produced, error message is printed to stdout with wrong timestamp when TZ offset is different from +0000:
```
Tue 16 Apr 17:45:07 CEST 2019
2019-04-16 17:45:21.889 INFO     PID: 27327 leapp: Logging has been initialized     
(...)
2019-04-16 17:45:37.465 INFO     PID: 27327 leapp.workflow: Workflow interrupted due to the FailPhase error policy
============================================================
ERRORS
============================================================
2019-04-16 15:45:37.289471 [ERROR] Actor: verify_check_results Message: Unsupported arch
2019-04-16 15:45:37.316866 [ERROR] Actor: verify_check_results Message: Ending process due to errors found during checks, see /tmp/leapp-report.txt for detailed report. …
```
=> Fix time offset of error messages

leapp/cli/upgrade/__init__.py, leapp/snactor/context.py, leapp/utils/audit/__init__.py
Previously checkpoints were loaded from the audit table in the database
and ordered by timestamp. However we ran into some problems were
timestamps were off due to some misconfiguration that caused the time
of the system being in the past after the reboot.
That resulted in leapp, trying to resume at a place that has been
already executed before.
This patch will change the ordering to use the row id, which is
sequential in SQLite.
=> checkpoints: Load checkpoints ordered by `id`

leapp/libraries/stdlib/__init__.py, tests/scripts/test_stdlib.py
This will be useful in the chrony check actor (https://github.com/oamg/leapp-repository/pull/139).
=> stdlib: add option to run() to ignore exit code

leapp/snactor/commands/discover.py
It's a fix to snactor to avoid spurious output to console:
`No handlers could be found for logger "leapp.linter"`
Now the `snactor discover` will print message like this:
`WARNING:leapp.linter:Actor <class 'actor.Biosdevname'> field produces should be a tuple of Models`
=> Add a simple logger to snactor discover command

leapp/models/fields/__init__.py, tests/scripts/test_models.py
https://github.com/oamg/leapp-repository/issues/203
Turns out base class fields aren't properly copied.
Current implementation of a fix makes eyes bleed, used purely
for bug localization.
=> Locate and fix bug with model inheritance

leapp/models/fields/__init__.py
Previous comment message didn't make it clear
that default values for List field have to be
copied not only in cases of inheritance.
=> followup 16ec262: update comment message

docs/source/unit-testing.md
Added info about `make install-deps` to the unit testing documentation.
=> doc: added information how to install test dependencies for each actor

leapp/actors/__init__.py, leapp/libraries/stdlib/api.py, leapp/messaging/__init__.py
With the current explanation of the function, it's not clear to me where the message will be shown to the user.
All it does is `print` only: https://github.com/oamg/leapp/blob/master/leapp/dialogs/renderer.py#L142
=> Make clear what show_message() from actor API does

leapp/models/__init__.py
Previously the value 'fields' of a Model could be potentially `None`
which is not usuable for `x in y` kind of checks. This raised a pylint
warning.
This patch fixes this minority.
=> models: Fix warning about memebership check

tests/scripts/conftest.py, tests/scripts/helpers.py, tests/scripts/test_messaging.py, tests/scripts/test_repository.py, tests/scripts/test_repository_actor_definition.py, tests/scripts/test_snactor.py, tests/scripts/test_utils_project.py
Instead of directly importing fixtures in tests
from helpers and adding a noqa/pylint disable
unused-import comment, pytest's fixture
discovery mechanism is utilized.
Noqa comments and imports have been cleaned up.
=> fixtures: introduce conftest.py

leapp/cli/__init__.py, leapp/cli/report/__init__.py, leapp/cli/upgrade/__init__.py, leapp/config.py, leapp/logger/__init__.py, leapp/utils/output.py
Co-authored by: Inessa Vasilevskaya <ivasilev@redhat.com>
Breakdown of changes:
- Added `leapp preupgrade`, which stops after Reports phase and displays info about generated report
- Moved all hardcoded paths to leapp config
- Refactored colorized decorative output
- Removed redundant direct writes to stderr
- Removed redundant dashes from option definitions
Thanks to Inessa for a working proof of concept for the preupgrade.
=> Add preupgrade subcommand + refactor config, paths and output colors

leapp/__init__.py, leapp/utils/workarounds/__init__.py, leapp/utils/workarounds/mp.py, tests/scripts/test_workarounds_application.py
Multiprocessing in newer versions received a fix that is not present in
the el7 version of python. In that fix the Finalize class verifies that
the callback is supposed to be run in the process that created the
object. This patch adds a workaround to introduce the same behavior.
=> workaround: multiprocessing.util.Finalize patched

leapp/logger/__init__.py
Previously fallback logging defaulted to DEBUG for all the things. This
patch introduces a more configurable approach that obeys --debug and
--verbose options and LEAPP_DEBUG/LEAPP_VERBOSE environment variables
instead.
=> snactor: Do not log debug by default

leapp/cli/upgrade/__init__.py, leapp/snactor/commands/run.py, leapp/snactor/commands/workflow/run.py, leapp/workflows/__init__.py
Previously on unhandled exceptions non of the applications did return
with a non zero exit code. This patch will introduce changes to the
framework and endpoint scripts to handle the situation and end with a
non zero exit code.
=> Exit non zero on unhandled exceptions and errors

leapp/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
Packaging
- Fix URL and Source0 in the SPEC file
=====================================================================
Framework
* Fixes
- Add workround patch for the multiprocessing library
- Exit non-zero on unhandled exceptions and errors
- Fix actor library loading, so libs do not have to be imported
in lexicographical order
- Fix buf with mode inheritance and list field (#203)
- Fix warning about membership check of models when (#503)
- Load checkpoint ordered by `id` instead of timestamp to prevent
issues with changed timezone (#499)
- Log on the ERROR level by default instead of DEBUG
- Print usage to stderr
* Enhancements
- Add phase name checking to workflow parameters
- Add the fetch_upgrade_report_raw() function to obtain raw report
data
- Create a dynamic configuration phase …
=> Release 0.8.0

leapp/cli/upgrade/__init__.py
We are able to hit the issue only on some machines (not sure why just
on some machines) during the scan of the repository. The issue
happens during the loading workflow modules.
Modified snippet of the err:
...leapp.repository.common: Loading workflow modules
...leapp.repository.system_upgrade_el7toel8: Loading workflow modules
Error: Undefined Model "ReportReference"
To fix that, import leapp.reporting inside the leapp.cli.upgrade
module to enure the Report model reference is loaded.
=> Fix: Undefined Model "ReportReference"

leapp/cli/upgrade/__init__.py, leapp/config.py, leapp/utils/output.py
Changes:
- report blocks aren't green in case of thrown exceptions
- only report files generated in the current preupgrade run are displayed
- currently comparison of modification time with stamp inside workflow's Execution is used
- slight reorder of newlines in output
=> Fix display of generated reports

leapp/libraries/stdlib/__init__.py, leapp/utils/audit/__init__.py, tests/scripts/test_audit.py
We already have "process-start" and "process-result" so
we do not need "process-end" as it does not add any
additional value.
=> Stop adding 'process-end' audit entry

leapp/cli/report/__init__.py, leapp/cli/upgrade/__init__.py, leapp/reporting/__init__.py, leapp/utils/report.py, tests/scripts/test_reporting.py
Introduce report composability, remove renderers
In order to easily extend report with more fields and
change the structure, we switch to using classes
(primitives) with configurable paths. This commit
also removes renderers as a standalone html report
should substitute it.
kudos to @shaded-enmity
=> Introduce report composability, remove renderers

leapp/snactor/fixture.py
return valid actor when there is another actor which name
is a substring of the actor in context.
E.g:
"persistentnetnames" vs. "persistentnetnamesdisable"
=> Fix _get_actor

leapp/utils/clicmd.py
Before that patch leapp preupgrade --nosuchflag would
show help information for topmost leapp command, not
usage information for leapp preupgrade.
That is a clumsy hack to access help info for the
exact subcommand that has been called.
The original problem was with parser.parse_args()
returning parser for topmost leapp command and not
the subcommand.
Any ideas and proposals on a more elegant solution are
welcome.
Closes-Issue:#550
=> Make leapp show help message for proper subcommand

leapp/libraries/stdlib/__init__.py
Most of the actors catching the `CalledProcessError as e` print `str(e)` translating to a suboptimal and non-descriptive message _"A Leapp Command Error occurred."_
Real-world example:
> Removing mount directory /var/lib/leapp/scratch/mounts/source_overlay/var/cache/dnf failed with: A Leapp Command Error occurred. 
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1746956
Also changing the way of printing the called command (`' '.join(args)` -> `str(args)`) as it has caused some confusion about missing or not missing quotation marks: https://bugzilla.redhat.com/show_bug.cgi?id=1718161
=> Improve failed command error message

leapp/reporting/__init__.py
This tag is required by PythonInformUser actor
which has been erroneously disabled because of
missing workflow tag in actor definition.
Unless this tag is added any preupgrade\upgrade
will fail when the actor definition is fixed.
=> reporting: Add PYTHON tag

Makefile
We had some issues with rpms in downstream when people installed
mix of upstream and downstream rpms by default because of higher
release there. After some discussions we will rather use release
100 instead of 1 for upstream builds by default.
=> Makefile: use release 100 for master branch

leapp/utils/report.py
TypeError: Unicode-objects must be encoded before hashing
=> Fix py3 TypeError during hashing

docs/source/unit-testing.md, leapp/snactor/fixture.py
Currently, when tested actor runs and tries to access workflow
config, it fails with WorkflowConfigNotAvailable. Apart from
feeding the actor a mock config model, we need to also make
it aware it should use the config.
=> Allow testing actors with config models

leapp/snactor/commands/workflow/sanity_check.py
Currently, in the command, we check whether we do not attempt
to consume a message before it is produced.
This will be added to our CI to perform a check on every PR.
=> Add snactor sanity-check command

leapp/messaging/__init__.py, leapp/messaging/commands.py, leapp/workflows/__init__.py
This patch introduces support for actors being able to let leapp skip
phases.
Phases can be skipped by an actor using leapp.messaging.commands.SkipPhasesUntilCommand
like this within the process method:
```python
self._messaging.command(SkipPhasesUntilCommand(until_phase='report'))
```
This will make leapp skip phases until it hits the 'report' phase.
=> Dynamic phase skipping support

docs/source/best-practices.md
The issue can be seen at https://leapp.readthedocs.io/en/latest/best-practices.html#use-convenience-exceptions-to-stop-the-actor-s-execution. The link is broken.
=> Fix doc reference to StopActorExecutionError

packaging/leapp.spec
We've got feedback that this file is needed for purposes of possible frontends (e.g. in cockpit). To not put obstacles here, adding the directory into the rpm, so it will exist always.
NOTE: It's not common practice to own anything in /var/log in the rpm, but as the path is documented (and there are other existing examples of rpms that are doing that, e.g. systemd) I think it could be ok to add it inside leapp.
=> Packaging: Add /var/log/leapp into the leapp rpm

.pylintrc, leapp/dialogs/renderer.py, leapp/exceptions.py, leapp/logger/__init__.py, leapp/models/fields/__init__.py, leapp/repository/__init__.py, leapp/repository/manager.py, leapp/snactor/commands/discover.py, tests/scripts/test_actor_api.py, tests/scripts/test_repository.py, tests/scripts/test_workarounds_application.py
Travis ci py3 check job was failing because of
some violations (supposedly merged in pre-release hassle
when ci wasn't reliable together with py3 check enablement).
=> lint: fix py3 job

leapp/libraries/stdlib/__init__.py, tests/scripts/test_stdlib.py
Add possibility to setup stdin (string or fd) when run subcommand
using the libraries.stdlib.run function. That's needed e.g. when
secret data should be used as input for the command and we do not
want to expose those data anywhere.
Fixes: #579
=> libraries.stdlib.run: expose stdin

leapp/actors/__init__.py, leapp/cli/upgrade/__init__.py, leapp/repository/actor_definition.py, leapp/workflows/__init__.py, tests/data/workflow-tests/actors/firstactor/actor.py, tests/scripts/test_workflow.py
In order to make leapp preupgrade non-interactive by
default the workflow and actor being executed need to
be aware of the mode they are processed in (preupgrade or
upgrade workflow) and skip dialogs accordingly.
This is controlled by the skip_dialogs method variable which
if set to False by default and is propagated into every
workflow.run and actor initialization method.
The preupgrade cli command now sets skip_dialogs=True for
workflow.run which makes all dialogs present to be skipped and
answerfile with all options commented out to be generated while
the upgrade command keeps the old behavior allowing questions to
be asked interactively if no option has been chosen and saved in
answerfile.
=> Introduce skip_dialogs functionality

setup.py
The requests package was missing when running leapp-repository unit tests - leapp framework was being installed by leapp-repository makefile [as a dependency](https://github.com/oamg/leapp-repository/blob/master/requirements.txt#L12), but without this dependency of leapp framework.
That caused an incorrect workaround on the leapp-repository side which will need to be reverted after this PR is merged:
https://github.com/oamg/leapp-repository/pull/410
=> Require 'requests' package during pip installation

leapp/cli/upgrade/__init__.py, leapp/utils/output.py
A complement of:
https://github.com/oamg/leapp-repository/pull/404
If the inhibition of unsupported upgrade is bypassed through `LEAPP_UNSUPPORTED`, a giant yellow warning appears.
=> Display a warning when upgrade is unsupported

docs/source/dialogs.md, leapp/actors/__init__.py, leapp/cli/upgrade/__init__.py, leapp/dialogs/dialog.py, leapp/libraries/stdlib/api.py, leapp/messaging/__init__.py, leapp/messaging/answerstore.py, leapp/models/__init__.py, leapp/reporting/__init__.py, leapp/topics/__init__.py, leapp/workflows/__init__.py, tests/data/workflow-tests/actors/firstactor/actor.py
Every time a Dialog.request_answers method is called
the corresponding dialog becomes registered with the
workflow and a DialogModel message containing specific
data is produced.
A connected patch in leapp-repository will introduce
an actor that would collect all messages of such kind
and produce proper Report messages with all the information
necessary for leapp answer\leapp upgrade stages.
=> Introduce DialogModel

leapp/cli/__init__.py, leapp/cli/upgrade/__init__.py
Change verbosity arguments from the base command to the upgrade related commands
The verbose and debug options it's now only available in commands where make sense to
increase verbosity.
A re-request of https://github.com/oamg/leapp/pull/574 by @alexandrepossebom, since he left.
=> Change verbosity arguments from the base command to the upgrade related commands

.travis.yml
testing on s390x is not included because centos image used doesn't have a build for s390x
=> enable testing on multiple architectures

docs/source/devenv-install.md
New Copr group "oamg" created to accomodate convert2rhel. The "leapp" Copr group is now deprecated.
The leapp project now resides in https://copr.fedorainfracloud.org/coprs/g/oamg/leapp/.
=> Update link in RTD to the new Copr project

leapp/libraries/stdlib/__init__.py, tests/scripts/test_stdlib_call_audit.py
For certain cases, e.g. getting binary data out of "dd" command,
we would like to skip encoding.
=> Expose encoding in run function

leapp/reporting/__init__.py, leapp/utils/report.py, tests/scripts/test_reporting.py
Previously workflow errors weren't shown in the
preupgrade report. This patch attempts to solve the
issue by introducing naive one way convertion between
ErrorModel and Report during fetch_report_messages
stage at the end of the workflow run. Database won't be
altered, no new objects added after that convertion.
A follow up may be suggested to refactor existing
errors with "steps needed\hints" information into proper
Report messages.
Closes-Bug: #575
=> Make error messages part of preupgrade report

leapp/utils/output.py
Before:
```
2020-01-10 16:07:29.037287 [ERROR] Actor: scan_subscription_manager_info Message: A subscription-manager command failed to execute
Detail: {u'details': u"Command ['subscription-manager', 'release'] failed with exit code 1.",
u'hint': u'Please ensure you have a valid RHEL subscription and your network is up.',
u'stderr': u"This system is not yet registered. Try 'subscription-manager register --help' for more information.\n"}
```
After:
```
2020-01-10 16:09:30.552676 [ERROR] Actor: scan_subscription_manager_info Message: A subscription-manager command failed to execute
Summary: 
Details: Command ['subscription-manager', 'release'] failed with exit code 1.
Stderr: This system is not yet registered. Try 'subscription-manager register --help' for more information.
Hint: Please …
```
=> Nicen up error detail display

leapp/cli/__init__.py, leapp/cli/upgrade/__init__.py, leapp/messaging/__init__.py, leapp/messaging/answerstore.py
Introduce a handy alternative to manual answerfile update to ease
the adoption of new preupgrade\answer\upgrade strategy.
This pr reflects only one part of the story - non-interactive
answerfile management. Prior to it the only option for
answerfile manipulation was to update it via some editor of choice;
now it is possible to register user choices for specific dialog options
as a single cli command:
leapp answer --section remove_pam_pkcs11_module_check.confirm=True \
--section may_not_be_present_section.option=False
Some refactoring to existing cli commands will also be
carried out as part of this patch.
=> leapp answer command for answerfile management

leapp/cli/upgrade/__init__.py, leapp/config.py, leapp/utils/output.py
At the end of "leapp upgrade" run we do not print message
about generated reports, in contrast to "leapp preupgrade"
where we do.
=> Fix: report msg not generated at the end of run

leapp/cli/upgrade/__init__.py, leapp/messaging/answerstore.py
Now by invoking leapp answer command with --allow-missing
flag it will be possible to register an option in the
answerfile.
This scenario may be useful for vagrant box setup and
doesn't affect the preupgrade\upgrade in any way.
leapp answer --section nosuchsection.key=value --allow-missing
=> Add --add flag to the leapp answer

.github/workflows/bot_pr_info_message.yml
This PR implements GitHub Actions workflow bot that comments the content of `message` as soon as new PR is opened.
`message` contains welcome message for the contributor, explaining what to expect and what to do in order to contribute to the Leapp project.
=> Added github actions workflow that comments in PR

packaging/leapp.spec
Originally we had troubles with dependencies and release processes
as we have been strict about versions of leapp and repositories,
specified in the leapp rpm. As well, we would like to ensure that
currently we will install all rpms when leapp tool is installed.
So we are going to keep dependency on leapp-repository, but
without a version specification. We are going to left the
reponsiblity for version check on repositories itself.
As well, python?-leapp rpms will provide new leapp-framework
capability informing about incompatible changes or new features that
affects leapp repository (like changes in stdlib). This one will
be more flexible than official versioning and can be updated per
PR (see comment in the spec file for more details).
As well, I added several new macros in the SPEC, so …
=> packaging: improve deps, polish spec and fix split of files

docs/source/dialogs.md, leapp/cli/upgrade/__init__.py, leapp/config.py, leapp/dialogs/components.py, leapp/dialogs/dialog.py, leapp/messaging/__init__.py, leapp/messaging/answerstore.py, leapp/models/__init__.py, leapp/utils/output.py, leapp/workflows/__init__.py
Previously the generated answerfile didn't contain the
expected choices for the boolean component (the only one
allowed component for actor dialogs so far).
=> answerfile: add available choices comment

leapp/utils/__init__.py, tests/data/workflow-api-tests/actors/secondphaseactor/actor.py
Previously non tuples for consumes or produces fields did get
converted to a tuple. However with the introduction of the workflow apis
this behavior got reverted and caused some breakage. This patch adds
this behavior back and extends it even to apis fields.
=> Tupelize non tuples consumes, produces or apis

leapp/snactor/fixture.py
ActorContext is used in tests to make a functional test of an actor.
When the apis field for Actors was introduced, this has been overlooked.
This patch adds the missing changes for this part of the code.
=> Fix ActorContext breakage due to get_api_models

docs/source/terminology.md, docs/source/tutorials.rst, docs/source/workflow-apis.md
This patch adds a basic tutorial for Workflow APIs how to use them, how
to define them and some best practises for them.
=> Add tutorial for Workflow APIs

leapp/actors/__init__.py, leapp/cli/upgrade/__init__.py, leapp/exceptions.py, leapp/messaging/__init__.py, leapp/utils/output.py, leapp/workflows/__init__.py, packaging/leapp.spec
Previously there was no separation of errors and inhibitors in the
reports and the output of the leapp tool.
This patch separates the output on the commandline and filters out the
inhibitor messages from the report to avoid duplication of the
information in the report.
=> Report inhibitors separately from errors

leapp/utils/output.py, leapp/workflows/__init__.py
Previously when leapp was executed not much was visible during the
upgrade except for the DNF output. This patch now introduces some
changes to the execution that shows what phase starts and which
actor gets executed.
Example output:
```
[root@localhost leapp]# leapp preupgrade
==> Processing phase `configuration_phase`
====> * ipu_workflow_config
IPU workflow config actor
==> Processing phase `FactsCollection`
====> * scanmemory
Scan Memory of the machine.
====> * tcp_wrappers_config_read
Parse tcp_wrappers configuration files /etc/hosts.{allow,deny}.
====> * scan_kernel_cmdline
No documentation has been provided for the scan_kernel_cmdline actor.
====> * storage_scanner
Provides data about storage settings.
====> * system_facts
Provides data about many facts from system.
====> * …
```
=> Show progress in non verbose executions

leapp/cli/upgrade/__init__.py, packaging/leapp.spec
The behavior is the same as the legacy `LEAPP_DEVEL_SKIP_RHSM`, except supported.
Requries Repo PR: oamg/leapp-repository/pull/482
=> Add --no-rhsm and LEAPP_NO_RHSM for skipping RHSM

leapp/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
- Add BuildRequires on python2-setuptools
- Add new dependency on python2-requests
- Add unversioned dependency on leapp-repository and provide
the leapp-framework capability in python2-leapp (see docs about
"new dependency mechanism") (#591)
- Move all leapp and snactor files into related rpms instead of python?-leapp (#591)
- Remove dependency on Jinja2
- Fix json export capabilities using serialization (#598)
- Add the DESKTOP tag for the leapp report (#612)
- Dialogs are non-interactive and redesigned significantly; but in beta support
(see the known issue)
- Introduce DialogModel that could be processed by actors to add related
information into the report (#589)
- Introduce Workflow API (see the Workflow APIs tutorial) (#618)
- Report inhibitors separately from errors on stdout …
=> Release 0.10.0

leapp/libraries/stdlib/call.py, leapp/libraries/stdlib/eventloop.py
To make tests work on Linux this patch introduces support for kqueue
on MacOS as an event loop for the call wrapper. This allows the
execution of leapp tests on MacOS and BSD systems.
=> Make stdlib.call work with kqueue

docs/source/el7toel8/envars.md
It has been replaced with a supported `--no-rhsm` option.
=> Remove LEAPP_DEVEL_SKIP_RHSM from docs

Makefile, docs/source/el7toel8/actor-rhel7-to-rhel8.md, leapp/messaging/__init__.py, leapp/snactor/commands/messages/__init__.py, leapp/snactor/commands/run.py, leapp/utils/workarounds/mp.py, tests/scripts/test_snactor.py
This patch introduces support for specifying a model which the actor
should consume for configuration data.
Using this feature requires to run an actor before which produces this
model and saves the output.
Jira-Task: OAMG-1092
Fixes #530
=> Add --actor-config to snactor run

docs/source/el7toel8/envars.md
Got partially inspired by https://github.com/oamg/leapp/pull/633.
=> Add missing env vars to the docs

leapp/cli/upgrade/__init__.py
Previously changes have been introduced that caused the debug/verbose
information not to be stored correctly to the database, which led to
different output behavior after reboot. (No debug/verbose output after
resuming the execution)
This patch changes the order when this data is processed so the
configuration is updated correctly.
JIRA-Taks: OAMG-3087
=> Fix handling of debug/verbose in {pre,}upgrade

docs/source/deprecation.md, docs/source/tutorials.rst, leapp/reporting/__init__.py, leapp/repository/actor_definition.py, leapp/snactor/commands/run.py, leapp/snactor/commands/workflow/run.py, leapp/utils/audit/__init__.py, leapp/utils/deprecation.py, leapp/utils/output.py, leapp/utils/report.py, packaging/leapp.spec, requirements-tests.txt, tests/data/deprecation-tests/.leapp/info, tests/data/deprecation-tests/.leapp/leapp.conf, tests/data/deprecation-tests/actors/deprecationtests/actor.py, tests/data/deprecation-tests/libraries/deprecation.py, tests/data/deprecation-tests/models/deprecatedmodel.py, tests/data/deprecation-tests/tags/deprecationphasetag.py, tests/data/deprecation-tests/tags/deprecationworkflow.py, tests/data/deprecation-tests/topics/deprecation.py, tests/data/deprecation-tests/workflows/deprecation_workflow.py
Introduction of the @deprecated decorator
This patch introduces the @deprecated Decorator allowing it to be used
for Models and functions/methods anywhere in the code.
The code makes use of the python warnings library and extends the usage
around this by allowing to pass the information since when the entity is
deprecated and pass a reason for the deprecation (e.g. replacement by
something else)
Log deprecation warnings to the audit db
Additionally in this patch logging of deprecations to the audit database
is introduced.
It will create a new event type 'deprecation' and logs details about
location and place.
Start reporting deprecation usages
On top of it this patch adds deprecation usages to the reports.
It will receive the items from the audit database.
If an item is deprecated for …
=> Introduction of the @deprecated decorator & integration into the workflow executions

leapp/utils/output.py
Previously the location of the pretty block for ERRORS has been
accidentally changed from stdout to stderr. This patch reverts this
mistake.
=> Fix output location for errors block

man/leapp.1, man/snactor.1
The existing manual pages are out of date and poorly formatted. This PR reformats the pages, adds info about missing commands/options/variables and structures them a bit more.
(I might have missed things, feel free to review.)
=> Update and reformat manual pages

.travis.yml, Makefile, requirements-tests.txt
Now if you're not a root, then the venv
automatically installed with requred dependencies
Also requirements-tests.txt updated to install leapp
in editable mode
fixes #646 
Now if you're not a root, it is enough to do:
`make install-test && make test`
=> Allow running as a not a root

leapp/messaging/answerstore.py, tests/scripts/test_answerstore.py
Previously dialog answers have not been tracked in the audit. This patch
introduces a new event type dialog-answer that will be emitted every
time a dialog answer is requested or received. This will report any
answers that are provided through answerfile or interactive reply.
=> dialogs: Create audit entries for dialog answers

leapp/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
- Bump leapp-framework capability to 1.3
- Preserve verbose/debug options during the whole upgrade workflow (#625)
- Print the informative error block to the STDOUT instead of STDERR (#623)
- Added new reporting tags: `PUBLIC_CLOUD` and `RHUI` (#650)
- Added the possibility to skip actor discovery to improve performance of tests when an actor context is injected directly (#638)
- Introduced the `deprecated` and `suppress_deprecation` decorators to support the deprecation process (#640, #653)
- Store dialog answers in the leapp.db (#651)
- The `suppress_deprecation` decorator causes a traceback in certain cases
- Updated and improved man pages (#633)
- Raising a missing exception with tests failing under py3 (#647)
- Added the --actor-config option to `snactor run` to specify a workflow …
=> Bump version to 0.11.0

man/leapp.1
=> manpage: Fix typo (enable-repo)

.pylintrc
pylint 2.6 was released on 2020-08-20 and introduced two new checks
which we cannot use due to Python 2:
- `super-with-arguments` (R1725)
- `raise-missing-from` (W0707)
Release notes: http://pylint.pycqa.org/en/latest/whatsnew/2.6.html
Virtually identical to https://github.com/oamg/leapp-repository/pull/582.
=> pylint: Disable checks introduced in pylint 2.6

docs/source/el7toel8/envars.md, man/leapp.1
That's only missing envar that is not documented and it is supported.
=> Document the LEAPP_ENABLE_REPOS envar

leapp/utils/deprecation.py, tests/data/deprecation-tests/actors/deprecationtests/actor.py
Two fixes:
1. The suppress_deprecation decorator cannot be used on every class. It's expected a class has the process method. Instead of confusing simple crash, raise an exception with a meaningful message when decorator is used on a class without the process method.
1. Handle 'nested' suppress of deprecation
Imagine case (pseudocode):
```pseudocode
(Ddep is deprecated entity)
@suppress_deprecation(Ddep)
def fA():
create Ddep
fB()
@suppress_deprecation(Ddep)
def fB():
create Ddep
```
In such a case, apps crashed, because we store information about
suppressed deprecation into the set. After you leave the fB function
the Ddep entity is removed from the set and after end of fA function
there is no way to remove it again - so the app crashes. This commit
fixes the problem.
The first case is …
=> Fix deprecation

.gitignore, leapp/utils/report.py, tests/scripts/test_reporting.py, tests/scripts/test_utils_report.py
The conversion of deprecation messages to reports was broken on Python3 because `haslib.sha256` requires byte string instead of Unicode (missing `.encode(utf-8)`). Added couple of tests to cover this part of code.
Also updated the .gitignore file so the `tests/scripts` directory is not ignored anymore.
=> Fix report deprecation

leapp/cli/upgrade/__init__.py
Add a missing blank space in the message. It currently will generate
"tostart" instead of "to start".
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>
=> leapp/cli/upgrade: add a missing blank space in the message

packaging/leapp.spec
In order build properly on public copr, we drop all the pytest
build dependencies as it is not necessary to run the tests during the
build.
Related: https://issues.redhat.com/browse/OAMG-3811
=> spec: Remove pytest residuals in spec file

leapp/utils/clicmd.py, leapp/utils/deprecation.py, tests/scripts/test_deprecation.py
Previously we have been using functools.wraps. However if any decorator
that uses functools.wraps is used, some code that relies on __wrapped__
being present, e.g. pytest, will fail on Python2. Switching to six.wraps
will solve this problem, as it introduces this change as well and solves
the missing __wrapped__ attribute.
=> Replace functools.wraps with six.wraps

leapp/dialogs/dialog.py, leapp/messaging/__init__.py, leapp/models/__init__.py, leapp/reporting/__init__.py, leapp/utils/report.py, tests/scripts/test_reporting.py
A 'key' field will be added to each report entry. Same report entries on different machines should have the same 'key' value.
From the user/contributor perspective the interface doesn't change, if the Key with the unique report key is not defined in the report entries passed to the create_report command, the framework will take care of stable identifiers by generating one from the required report fields or will raise a ValueError in case LEAPP_DEVEL_FIXED_REPORT_KEY environment
variable is defined.
This fallback behavior will be the last resort once all actors in the leapp-repository are updated.
=> Add a stable report identifier

leapp/reporting/__init__.py
The stable report id patch was using configure_logger instead
of logging.getLogger.
=> reporting: use logger properly

packaging/leapp.spec
Regarding the new functionality (reporting.Key) providing the stable
key id for every report, the framework version should be bumped to
keep stuff compatible.
=> Bump framework_version to 1.4

packaging/leapp.spec, report-schema-v100.json, report-schema-v110.json, requirements-tests.txt, tests/data/report-schema/leapp-report-stable-key.json, tests/data/report-schema/schemas/report-schema-v100.json, tests/data/report-schema/schemas/report-schema-v110.json, tests/scripts/test_reporting.py
Generated by https://jsonschema.net and adjusted manually.
OAMG-4263
=> Introduced a JSON schema of a leapp report

leapp/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
- Add JSON schema of leapp reports for validation (#681)
- Bump leapp-framework capability to 1.4 (#684)
- Fix Py2/Py3 issues for unit-tests relying on __wrapped__ for decorators (#674)
- Add a stable report identifier for each generated report (#669)
- Add a possibility to overwrite virtualenv name for testing  `$VENVNAME` (#675)
- Add a way to override default python version using `$PYTHON_VENV` (#675)
Related leapp-repository release: https://github.com/oamg/leapp-repository/releases/tag/v0.13.0
=> Release 0.12.0

report-schema-v110.json
This should fix version: 1.0.0 that has been obviously put there
by mistake.
=> Change version field of report-schema-v110.json

docs/source/deprecation.md, docs/source/el7toel8/deprecation.md, docs/source/el7toel8/leapp-repository-el7toel8.rst
Just document the stuff that is already deprecated. Added:
- a new document for the deprecated stuff in the el7toel8
leapp repository
- a new section about deprecated stuff in leapp itself
The main deprecation document is pretty long now and the section
for the deprecated list in leapp is not good there. However I do not
see better way how to do it right now. The doc needs to be split
for sure in future, but this is not scope of this PR.
=> Doc: add lists of the deprecated functionalites

leapp/libraries/stdlib/call.py
In short, we close a fd before the select.epoll.unregister(fd)
is called. The function originally ignored closed fd (EBADF) however
it's changed since Python 3.9+
Close the fd after it's unregistered.
See:
- https://bugs.python.org/issue39239
- https://github.com/python/cpython/commit/5b23f7618d434f3000bde482233c8642a6eb2c67
Thanks @shaded-enmity for the fix.
Fixes: #682
Co-authored-by: Pavel Odvody <podvody@redhat.com>
=> Fix the call function from the stdlib library on Python 3.9

res/docker-tests/Dockerfile, res/docker-tests/Dockerfile.centos7, res/docker-tests/Dockerfile.centos8
Due to the docker hub rate limitation we will switch to be using the
registry.centos.org registry for our tests.
=> Tests: Use centos repository for docker images

.pylintrc, tests/scripts/test_reporting.py, tests/scripts/test_utils_report.py
There have been some new warnings/errors during the linting process,
that probably came with a new version of pylint etc.
This patch addresses those.
=> linting: Fixing reporting related warnings/errors

Makefile
During the previous fix, I overlooked the git pull of the container in
the Makefile. This caused a failure at that point. This PR adds the
second location where this is happening.
=> testing: Adding second place for centos registry

docs/source/el7toel8/envars.md, man/leapp.1
Documents two new environment variables introduced in oamg/leapp-repository#654 in upstream docs and the manual page.
=> Document leapp data file service envars

Makefile
The default shell in Makefile is `sh` and since bashisms are used in the
Makefile, some of the targets fail, depending on setting of the system
(not an issue on vanilla Fedora where `/bin/sh` is a symlink to `bash`).
=> Set the default shell used in Makefile to bash

.github/workflows/tmt-tests.yml, Makefile
The actual command that triggers a new test on TF service is commented out as
it would fail at this moment, because there are no tmt plans ready in the
repository.
Depends on: #704
=> Add GitHub workflow that triggers tmt tests in Testing Farm service

.github/workflows/tmt-tests.yml
This patch fixes incorrect TF request and also adds print of the request/response jsons that can be enabled by setting the `ACTIONS_STEP_DEBUG` secret to `true` (this also enables step debug logging).
=> Fix incorrect request to TF service

res/docker-tests/Dockerfile, res/docker-tests/Dockerfile.centos7, res/docker-tests/Dockerfile.centos8
The easy_install script is not usable anymore since the html page
changed the format and the script is not able to discover required
python packages anymore. Instead of that, install pip from centos
(includes installation of the EPEL repository), update it to version
we require and continue..
As well, to omit possible additional problems in future with pip for
Python3, let's install in the container python3-pip and update it
to the very same version (v20.3.4) too.
Co-Author: Petr Stodulka <pstodulk@redhat.com>
=> Fix the pip installation in Dockerfile for unit-tests

.github/workflows/tmt-tests.yml
Artifacts to be installed should come in build_id:chroot_name form.
Ex. "artifacts": [{"type": "fedora-copr-build", "id": "2220887:epel-7-x86_64"}]
=> Pass copr build properly

docs/source/el7toel8/deprecation.md
The new solution around the target userspace container, the upgrade
initramfs, and the target initramfs has been merged in leapp-repository
upstream for el7toel8. With that, 4 models has become deprecated as
these have been replaced by new models.
Deprecated models:
- RequiredTargetUserspacePackages
- RequiredUpgradeInitramPackages
- UpgradeDracutModule
- InitrdIncludes
=> DOC: update current devel deprecation regarding initramfs stuff

leapp/models/__init__.py
Previously there was a reference for Models created for every symbol
attempted to being imported from leapp.models, however pytest tries to
import `_pytestfixturefunction` which is not a model obviously.
To work around pytest causing failures because of that, private symbols
are being filtered from the model reference creation magic.
For reference, this is what you would see running pytest without this fix:
```
....
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise …
```
=> models: Do not make references for private symbols

.github/workflows/pr-welcome-msg.yml
Change made after discussion with @Rezney, to be safer with unverified action. (more [here](https://julienrenaux.fr/2019/12/20/github-actions-security-risk/))
Action needs to be enabled in organization settings, see [docs](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#managing-github-actions-permissions-for-your-organization).
=> Replace action tag with sha in PR welcome msg action

Makefile, packaging/leapp.spec
The SPEC file has been simplified to make the maintaining simple for
people. As the set of changes seems biger regarding that, here
is the list of changes explicitly:
* The building for Python2 and Python3 is now exclusive.
Python2 is supported only on RHEL 7. For all newer systems
(Fedora including) build just with Python3.
* Additionaly the python3-leapp packages provides leapp-framework
as expected.
* Remove auto generated python(abi) dependency on Python3 systems
Various versions of systems (RHEL 8, RHEL 9, Fedora 33, Fedora 34)
use different versions of Python. This means the python(abi) is
different on each system, however leapp packages (excluding the
deps metapackage) has to survive the upgrade of the system
untouched. This is not possible when requirements on python(abi)
is …
=> Packaging: prepare building for RHEL 8+  and Fedora (iow, for Python3)

leapp/repository/__init__.py, leapp/repository/manager.py
The RepositoryManager.lookup_actor function returns always just one
Actor or None. However, in case the actor of the same name is specified
in multiple repositories I would like to have an info about all these
actors. Currently I am not sure whether there is a mechanism to prevent
people having actors with identical name in multiple repositories when
leapp is running, but so far, tests do not react on the situation when
some actors of the same name exists. For now, creating this private
function to be able to run unit tests for actors of specific name
in all available repos.
@vinzenz @Rezney  somthing for the discussion guys. I choosed this way (the private method) for now as we will not introduce functionality anyone should be care of so easy to remove whenever we want in the future and …
=> Add the _lookup_actors function into the repo manager

packaging/leapp.spec
There is difference in the automaticly generated dependencies when the RPM is built in the internal COPR for RHEL-8 or when it's built in public COPR for EPEL-8:
- EPEL-8: `/usr/bin/python3.6`
- RHEL-8: `/usr/libexec/platform-python`
Extending the `__requires_exclude` macro to drop both.
In case the dependency is not dropped, the `leapp` rpm is automatically removed during the upgrade process which ends with the emergency mode as we are not able to run leapp after the rpm transaction is processed.
=> Drop dependency on /usr/bin/python3.6

.github/workflows/tmt-tests.yml
As tmt-plans repository now contains morf tests for convert2rhel this
is needed to filter out tests that make no sense for leapp.
=> Add name parameter to the tft request

leapp/utils/clicmd.py
A change introduced in the stdlib argparse module accidentally caused
all subparsers to become optional instead of required as in python 2.7.
This change therefore causes leapp to print nothing and exit with error
code 0 when being executed without any arguments.
This commit marks the subparser action as required, so that the
python3.6 module recognizes this situation and prints the usage message.
To provide a meaningful message on python3.6 the subparser action was
edited to use 'command' metavar and the 'title' option was dropped.
Tasks to be done:
=> Fix leapp prints nothing when running with no args on python3.6+

leapp/utils/audit/__init__.py
This patch introduces an optimization of the database access when the
LEAPP_DEVEL_DATABASE_SYNC_OFF environment variable is set.
This causes to write to the database up to 20 times faster than normal,
depending on the underlying hard drive and file system.
I managed to increase the speed leapp preupgrade from 9 minutes 7
seconds to 26 seconds.
However this feature comes at the cost of risking database corruption,
in case of powerloss or OS crashes. According to the SQLite
documentation, application crashes are safe.
Since this option poses a potential risk, it is deemed for now
a development option only and will help to speed up our CI systems.
=> devel: Speed up leapp database writes by disabling synchronization

packaging/leapp.spec
The leapp tool doesn't depend on leapp-repository anymore. However,
when no leapp repository is present on the system, there is nothing
to do usually when leapp is installed as all subcommands for leapp
should be provided by specific leapp repositorise.
I wanted to remove the dependency completly and keep it just in
downstream, however not sure whether that could be a good way.
So let's keep the requirement to provide the leapp-repository
at least as a capability for rpms that want to use leapp on RHEL 7.
People are going to be instructed to install e.g. `leapp-upgrade`
or `leapp-convert` to install everything what they need for the
action they want to do.
It should be merged together with https://github.com/oamg/leapp-repository/pull/701 ideally, but it's not hard requirement.
=> Packaging: requires leapp-repository on RHEL 7 only

leapp/utils/clicmd.py
Extending leapp command to support traditional argparse-style choices
and default arguments.
=> Add cli support for choices and default

.github/workflows/tmt-tests.yml
Instead of specifying which tests to run (leapp, integration, e2e)
switch to specifying which tests to skip (c2r, sap).
=> Change tmt plans filtering

packaging/leapp.spec
Regarding the recent changes, we provide new functionality regarding
get_*_path() functions - so the shared/common paths that do not
require execution of actors, can be used. This is useful e.g. when
we want to get specific files for the purpose of commands. Previous
use in actors is not affected by this change, however, use of these
functions outside of actors (e.g. in leapp commands) requires the
new implementation strictly.
Fixes: #742
Relates: https://github.com/oamg/leapp-repository/pull/753
=> Bump leapp-framework to 2.1

packaging/leapp.spec
On RHEL 8 it could happen that people replace the original Python 3.6
by Python 3.8+. However, regarding the build & installation process,
we can support just ONE version of python per RPM - except the newer
version of python on the upgraded system, which is handled during
the upgrade by our workarounds. For that reason we put the abi
dependency back into the metapackage for RHEL 8 system only.
Example of the problem on RHEL 8:
```
-bash: /usr/bin/leapp: /usr/bin/python3.6: bad interpreter: No such file or directory
```
=> Add python(abi) == 3.x deps for RHEL 8+ into the meta-pkg

packaging/leapp.spec
The previous fix with the python(abi) was wrong as it still could
lead into the situation when the system python is not installed,
because platform-python provides such ABI still. The correct fix
is to add dependency on python3 as such a dependency refers always
to the main python version for particular system despite the name
of the rpm package.
=> Fix of fix for Python 3 depenencies

packaging/leapp.spec
Our packages have to stay noarch in future for various reasons.
To reduce stress of some people, let's make it more explicit that
if someone see the change from noarch to arch specific packages,
the change must not be merged.
=> Packaging: Added note into the spec about noarch

leapp/config.py, leapp/utils/report.py, man/leapp.1, tests/scripts/test_reporting.py
In order to be completely safe that any changes that land in leapp
reporting don't break older clients there should be a possibility
to force specific version of json schema.
Currently there are 2 schemas that are actually backward compatible,
but it may not be the rule soon.
This patch adds a --report-schema option to leapp preupgrade/upgrade
commands that force sticking to specific version of the report schema.
For example with --report-schema '1.0.0' passed there will be no stable
keys in the report messages, as those have been added in the recent
'1.1.0' report schema.
=> Control leapp-report format

.github/workflows/tmt-tests.yml
Both 7to8 and 8to9 upgrade paths will be tested for every
upstream pr.
For rare situations where leapp pr had to be tested together with
specific version of leapp-repository pr enable the same
'/rerun dependent-leapp-repository-pr-num' mechanism as is present
in leapp-repository's tmt-plans workflow.
OAMG-6387
=> Introduce 8to9 regression testing

utils/get_latest_copr_build
7to8 and 8to9 upstream regression testing has shown that we
need some tooling to get most recent leapp-repository's master
copr build id.
So shamelessly copying the refactored utils/get_latest_copr_build
script from leapp-repository to be used in tmt-tests workflow.
=> Create get_latest_copr_build script

.packit.yaml
When a PR build is created by PackIt it contains different hash
of the commit than the latest in the PR. This is caused by the
default behaviour, when PackIt merge locally the PR changes to the
master.
As we like this idea to test stuff how it works when applied to the
master, it has several problems:
- sometimes a PR could have conflicts with master and the build
will not be created in such a case; but for some simple testing
it could be a little bit annoying for someone
- it's not possible to install a build to a specific commit using
the commit short-hash; sometimes it's usefull when you want to
really try the build from specific commit and it's hard to find
the right one in such a case
So let's set `merge_pr_in_ci` to `false` so the created build
is identical to the one in the PR.
=> Packit: stop merging with master for PRs builds

.github/workflows/tmt-tests.yml
In case of /rerun 42 copr build for leapp-repository*PR42* would
be passed;
In case of /rerun the latest master build's id of leapp-repository
will be passed.
=> Always pass 2 copr builds for testing

leapp/dialogs/dialog.py, leapp/messaging/answerstore.py, packaging/leapp.spec
Previously a DictProxy entry was passed as part of
{dialog_section: entry} data to save in store which
failed during serialization.
=> Fix TypeError during JSON serialization in dialogs

leapp/messaging/answerstore.py
Currently we have 2 reason fields in dialogs
- one 'generic', for the dialog itself
- one specific just for the particular user question
The framework now prints only the first one, which in some cases
hides important text connected to the particular question. Printing
both reasons now.
=> Dialogs: print the reason for question in the answerfile

leapp/utils/workarounds/mp.py, tests/scripts/test_actor_api.py
In Python 3.9 tests fail on macos because multiprocessing does no longer fork, to prevent this behavior from changing at all this PR adds a workaround for this.
Related issue #690
=> Python 3.9 compatibility

leapp/logger/__init__.py
Previously we started using logging before it had been initialized.
Which resulted in leapp stopping to log for some logger names the debug
output. We did not know why this happened. It turns out that fileConfig
from the logging library has a parameter disable_existing_loggers which
is by default set to True and will set all loggers that have existed
before the call to fileConfig to disabled. Which in turn will make them
stop logging of course.
This patch will change this behaviour and set disable_existing_loggers
to False in order to have existing loggers be still enabled.
=> logging: Fix missing logging

.packit.yaml
and be able to specify the precise list of deps needed to create the
SRPM: there are no extra for leapp, so the list is empty
Details: https://packit.dev/posts/copr-srpms/
=> packit: build SRPM in Copr

.github/workflows/pr-welcome-msg.yml
A necessary change that should finally represent the changes of
the previous quarters: several jobs disablement and new CI
introduction.
No more e2e and internal copr build jobs, /rerun command finally
documented.
OAMG-5822
=> Update welcome message

.pylintrc, Makefile, leapp/actors/__init__.py, leapp/dialogs/dialog.py, leapp/dialogs/renderer.py, leapp/libraries/stdlib/eventloop.py, leapp/models/__init__.py, leapp/reporting/__init__.py, leapp/repository/__init__.py, leapp/snactor/commands/new_actor.py, leapp/snactor/fixture.py, leapp/snactor/utils.py, leapp/utils/__init__.py, leapp/utils/actorapi.py, leapp/utils/audit/contextclone.py, leapp/utils/report.py, res/container-tests/Containerfile.ubi7, res/container-tests/Containerfile.ubi8, res/container-tests/Containerfile.ubi9, tests/scripts/test_reporting.py, tests/scripts/test_rerun.py
Because unit tests in upstream were not enabled for some
time the following technical debt accumulated.
This patch takes care of make lint command only, not the
unit tests.
Related: OAMG-6723
=> Necessary fixes to make linter happy again

.github/workflows/tmt-tests.yml
This should allow root auth on every guest, even those that
don't have it enabled by default.
This patch also pins tft github action to 1.2.10.
OAMG-6748
=> Pass enable root auth post-install-script

leapp/cli/__init__.py
Simple check that ends leapp process if it wasn't executed with root privileges.
Jira ref: OAMG-6476
=> Check root privileges at the start of leapp execution

leapp/reporting/__init__.py, leapp/utils/report.py
As we substituted Tags and Flags with Groups recently, it has
impact on original detection of inhibitor inside leapp-repository
which is not compatible with the new reporting implementation.
As it could happen that new framework and old leapp-repository could
be installed on the system, the consequence in such a case is that
inhibitors will not be caught and user running:
```
```
could hit various serious issues. This change make sure we keep the
original functionality working, until we drop flags & tags
completely, providing enough time to everyone to adapt to new
changes.
=> Preserve the original inhibitor detection valid for now

Makefile
Adds `test_container` Makefile target for running tests locally in
containers. This way tests can be run on all the different versions
locally.
Run `make test_container` to run tests in container. By default `rhel8`
container is used. This can be changed by setting `TEST_CONTAINER`
environment variable.
There is also `test_container_all` target which runs tests in all
available containers.
Available containers are rhel7, rhel8, rhel9.
Run `make clean_containers` to cleanup container images.
Containerfiles in `/res/container-tests/` are reused. This means that
`pip` installs test dependencies on every run. However this doesn't seem
like a significant slowdown. In future caching could be added at the
cost of creating different Containerfiles.
Building new image on every run also doesn't …
=> Add Makefile target for running unit tests in containers

.github/workflows/tmt-tests.yml
Add 2 more testing paths to regular regression testing
triggered on /rerun.
OAMG-7416
=> Enable 7.9->8.6 and 8.7->9.1 testing

.github/workflows/reuse-tests-7to8.yml, .github/workflows/reuse-tests-8to9.yml, .github/workflows/tmt-tests.yml
Instead of vague distro=7 and distro=8 use
7.9 and 8.6 respectedly as our refactored regression
tests now use.
This should fix the "no plans found" issue with 8.6-rhui
upgrade as well as continue running e2e test as part of
8->9 integration tests.
=> Be more specific about distro

leapp/models/fields/__init__.py, packaging/leapp.spec, tests/scripts/test_serialization.py
As models have to be JSON-serializable and byte
fields apparently don't fit in, let's introduce
a special model field type that could be used in
such situations.
OAMG-4306
=> Introduce a Blob model field

docs/source/deprecation.md, leapp/reporting/__init__.py
Apply official deprecation process for Tags and Flags
primitives that has been superseeded by Groups.
OAMG-7262
=> Deprecate Tags and Flags

leapp/cli/__init__.py, leapp/exceptions.py, leapp/utils/clicmd.py
Previously when leapp was executed but no cli commands were installed,
the leapp execution failed with an exception.
This patch will add specific handling to this particular scenario and
return a 1 exit code.
Jira ref.: OAMG-7148
=> cli: Handle missing commands gracefully

leapp/utils/workarounds/__init__.py, leapp/utils/workarounds/fqdn.py, tests/scripts/test_workarounds_application.py
Add a wrapper around `socket.getfqdn()` which returns `invalid.hostname`
in cases where hostname, or rather FQDN contains non-ascii and
non-standard characters.
This works around the issue that non-ascii characters can't be inserted
into leapp database.
For the standard for hostnames see `hostname(7)`. The current
implementation doesn't check for length of hostname nor it's individual
segments.
Jira ref: OAMG-7102
=> Add a workaround around non-ascii and non-standard FQDNs

docs/source/deprecation.md, leapp/__init__.py, leapp/reporting/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
-  bumped leapp-framework to 3.1 (#677)
- Fixed a problem where passing environment variables to an executed child process modified the environment variables of the parent process (​​#784)
- Ignore invalid FQDNs (#790)
- Deprecate `reporting.(Tags|Flags)`, replaced by `reporting.Groups` (#677, #781, #788)
- Introduce `is_inhibitor` function (#677)
- Introduce a `Blob` model field (#789)
- Introduce new report JSON schema v1.2.0 (default: 1.1.0) (#677)
- Handle missing CLI commands gracefully (#785)
- Requires to be executed by root only (#775)
=> Release 0.15.0

leapp/messaging/__init__.py
Previously only presence of one section in the answerfile
has been verified, which led to false-positive preupgrade
reports when some other key has been present in the
dialog section instead of the required one.
OAMG-7521
=> Make checks for missing answers more strict

.gitignore, Makefile, res/container-builds/Containerfile.centos7, res/container-builds/Containerfile.fedora_generic, res/container-builds/Containerfile.ubi8
Add `build` target to build locally and `build_container` to build
locally in a container. Building in containers has the benefit of being
able to build on all the different platforms e.g. both on  el7 and el8.
Run `make build` to build locally.
Run `make build_container` to build in a container. Note that
BUILD_CONTAINER environment variable must be set.
Run `clean_containers` to clean up container images used for building.
The containers are built from Containerfiles in `res/container-builds/`.
Since Containerfiles for all the Fedora versions would differ only in the `FROM`
statement, a generic Containerfile `Containerfile.fedora_generic` is
used and the `FROM` statement is inserted in the Makefile.
For el7 builds CentOS 7 container is used, because rpm-build package
is not available in …
=> Add Makefile target for building RPMs locally and in containers

docs/source/el7toel8/actor-rhel7-to-rhel8.md
prefer having this documented instead answering everyone questions why it does not work when it is in documentation. At least until it is fixed.
=> Document workaround for the broken snactor

leapp/snactor/commands/workflow/sanity_check.py
Previously, if a Model was being consumed by actor before it was
produced,  `snactor sanity-check` reported a failure. This however
blocks some use case in leapp-repository now, where there is the
possibility to supply user data and it is being verified before in a
later stage it actually is used. This sanitization actor causes this
check to fail and would force an ugly workaround by having a dummy actor
pretending to produce the message earlier.
This patch will introduce two ways of handling this situation by
ignoring the models. Either each model can be specified as a commandline
option --ignore or a path to a file containing a list of such models can
be supplied via --ignorefile.
Any of those specified model names supplied via --ignore or the
ignore file will no longer be considered a …
=> snactor.sanity-check: Add option to ignore models

Makefile, packaging/leapp.spec
The nature of the content stored in the ``/var/lib/leapp`` directory requires stricter permissions.
=> change the permissions for /var/lib/leapp directory from '755' to '700'

leapp/exceptions.py, leapp/repository/actor_definition.py
Previously when leapp would be running actors, any exceptions raised by
those actors in child processes would only be output to stderr,
while the main process would only have the exit code to examine.
Consequently, there was no real way to log occurring exceptions -
only providing the aforementioned exit code was possible.
This patch adds a pipe between the main and the actor processes,
through which a formatted exception + traceback string is provided to
the main process.
This string is then packaged into the `LeappRuntimeError` thrown from the
process, to be utilized downstream in
workflow/command code.
This should serve as a step to closing #692 - although actually logging
the exception traceback likely should be done on the `leapp-repository` side.
=> Expose tracebacks from actor exceptions

leapp/utils/output.py, tests/scripts/test_utils_output.py
When leapp executes in a Python 2 environment, an actor encountering an error can cause further issues if the message string provided to `leapp.utils.output` contains non-ASCII characters. 
This line in output.py is the main problem:
```python
sys.stdout.write("{red}{time} [{severity}]{reset} Actor: {actor}\nMessage: {message}\n".format(
red=Color.red, reset=Color.reset, severity=model.severity.upper(),
message=model.message, time=model.time, actor=model.actor))
```
As you can see, this line isn't Unicode in Python 2, which is why trying to format it with u-strings directly will end up causing an error like the one below:
```
Dec 05 08:19:44 localhost upgrade[437]: Traceback (most recent call last):
Dec 05 08:19:44 localhost upgrade[437]:   File "/usr/bin/leapp", line 9, in <module>
Dec …
```
=> Encode output.print_error message to avoid UnicodeEncodeError when displaying errors

.github/workflows/tmt-tests.yml, .pylintrc
Upstream tests should be testing bleeding edge features using latest bleeding edge leapp data.
So let's pass LEAPPDATA_BRANCH=upstream as test env var.
=> Use upstream assets for tests

.github/workflows/reuse-copr-build.yml
After some unknown changes around COPR, the building
command and the used COPR configuration file needs to be
updated.
OAMG-8876
=> Make copr-build functioning again

leapp/reporting/__init__.py, leapp/utils/report.py, tests/scripts/test_reporting.py
When a remediation command is printed that manipulates non-ascii but totally valid utf-8 filenames, leapp should not give out any tracebacks upon report generation.
Related-to: OAMG-8629
=> Improve handling of remediations with non-ascii data

.github/workflows/pr-welcome-msg.yml
OAMG-8977
jira-sync bot will be decommissioned based on usage data of  'review please' functionality
change is same as in  https://github.com/oamg/leapp-repository/pull/1073
=> Remove 'review please' mention from welcome PR message

leapp/dialogs/dialog.py, tests/data/actor-api-tests/actors/first/actor.py, tests/scripts/test_actor_api.py
`choices` is not an attribute of `Component` only of some of its subclasses
=> Dialog creation fails for a Component without choices

.github/workflows/reuse-copr-build.yml
copr config username for a dependent leapp-repository PR build case wasn't changed in the 5ddce5a. This patch should address that.
OAMG-8876
=> Make copr-build for /rerun 42 functional again

leapp/utils/output.py
The `isinstance` type check in `report_info` checks the type of an incorrect variable. This fixes the issue.
=> Fix invalid type check

leapp/messaging/__init__.py, leapp/workflows/__init__.py
Now when an exception is thrown during actor
execution it won't be shown only on stdout, but
will appear in leapp.db and leapp report as high
risk report message.
OAMG-4186
=> Save actor tracebacks in leapp.db

leapp/utils/output.py, packaging/leapp.spec
Previously only the paths to reports were printed and as a result the reports were easily missed.
Leapp now prints a list of HIGH and MEDIUM priority reports along with a summary of number of reports with individual severities to make reports more visible.
This change is incompatible with previous versions of leapp so the leapp-framework is going to be bumped to v 4.0. The leapp-repository needs to be updated also to be able to use the new leapp as it requires an update of CLI commands. 
Jira ref.: OAMG-8586
Requires: https://github.com/oamg/leapp-repository/pull/1061
=> Add reports summary to the output

leapp/libraries/stdlib/__init__.py, leapp/libraries/stdlib/call.py, tests/scripts/test_stdlib_call_audit.py, tests/scripts/test_utils_project.py
Currently, if the executable required in `run` does not exist (or is not executable), the child process's code is not replaced by `os.execvpe` function and it raises the OSError instead. However, the parent process does not get this OSError. It consumes exit code, stderr, ... of the child process. So in case the code does something like this:
```
try:
result = run(['non-executable'])
except OSError:
pass
except CalledProcessError:
```
the child process passes and do whatever.. In case it ends with zero exit code, the obtained result is usually something totally different than expected in actors. Also there could be problems with non-idempotent code, when some actions could be done twice (once executed by the child, send time executed by the parent [current] process).
We have realized that …
=> stdlib.run: Fix missing executable

leapp/reporting/__init__.py, leapp/utils/output.py, leapp/utils/report.py, packaging/leapp.spec
This patch improves the leapp output format. The "REPORT" section is
renamed to "REPORT OVERVIEW" and in addition to high and medium priority
report titles it contains also inhibitor titles and actor and short
error message for errors.
The long (possibly thousands of lines) detailed errors messaged and
tracebacks are kept in the "ERRORS" section. The inhibitors section is
removed, because it's contents are now in the report overview.
=> Change output format to report overview

docs/source/el7toel8/deprecation.md, docs/source/el7toel8/envars.md, leapp/__init__.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
Release 0.16.0
-  Provide leapp-framework 5.0 (#818, #840)
- Improve processing of reports with UTF-8 characters (#821, #828)
- Fix info reporting with only one path to log (#834)
- Include tracebacks of actors into the leapp.db (#832)
- Dialog creation fails not more for a component without choices (#826)
- Empty report is generated correctly (#828)
- Fix processing data in remediation instructions with non-ascii characters ()
- Improve report summary output to make it more visible (#818, #840)
- Fixed the call when the execute cannot be performed (#836)
- changes related just to stdlib - under leapp/libraries/stdlib
- update the deprecation list for the leapp-repository 0.19.0
- update the list of envars
=> Release 0.16.0

leapp/utils/report.py
The external links were only included in the `leapp-report.json` and its `.txt` version was lacking this essential information. I didn't find any other problems regarding the information that is not included in one or the other format. Although the OAMG-9665 seems to be related to this. Do you think that it should be fixed in this PR as well?
Jira: OAMG-8553
=> add external links to the leapp-report.txt

leapp/utils/report.py
Previous commit introduced couple of issues regarding details of reports that could lead to situations like:
* remediation instructions has not been printed when non-ascii characters have been present
* possible unwanted empty line when remediation has been specified but relative symlinks hasn't
* if the URL title contained non-ascii character, it has been broken too (on py2)
This should handle all mentioned problems when generating the txt file.
=> Report txt: fix printing of non-ascii details

docs/source/contributing.md, docs/source/python-coding-guidelines.md
* We tell people not to use `_`.  Now we advise them on what to use instead.
* Also fix link syntax in the contribution guide.
=> Recommend descriptive variable name for discarded values.

leapp/libraries/stdlib/call.py
In `stdlib._call()`, we lookup whether the command that we are going to call is present on the user's PATH.  Two changes are made to the function:
* Simplify the lookup of PATH now that we are making a copy of the environment's PATH.
* Add compat code to use `shutil.which()` on Python3 (while still using `distutils.spawn.find_executable()` on Python2).  As noted in the comment, `which()` will be needed when the code runs on Python-3.12.
=> Python-3.12 compat and refactor of path determination.

.packit.yaml
Having extended coverage for leapp-repository tests we just can't leave leapp behind.
=> Add RHUI-8.8 and RHUI-8.9 tests

.packit.yaml
That' an adoptation of leapp-repository's packit update and refactoring introduced in PR1176.
OAMG-10855
=> Update packit with currently supported upgrade paths

.packit.yaml
Now for basic sanity test verification in upstream tests tagged by 'tier0' will be used instead of 'sanity'.
RHELMISC-3211
=> Update packit config after tier redefinition

leapp/utils/output.py
Users who do not understand why they should read the generated leapp report. They are missing that the console output is just a summary overview of the report itself.
Rewording the msg little bit to make it explicitely clear that report contains more details about discovered problems and possible remediation instructions.
Also reverted order of the report about generated report files, making `.txt` version first.
Jira: RHEL-25406, RHEL-25407
```
============================================================
REPORT OVERVIEW                       
============================================================
Upgrade has been inhibited due to the following problems:
1. Found GRUB devices with too little space reserved before the first partition
2. Leapp detected loaded kernel drivers which have …
```
=> Reword the report msg in the console output to note remediations

leapp/cli/__init__.py, leapp/config.py, leapp/exceptions.py, leapp/utils/lock.py
This change addresses the potential risk of running multiple instances of Leapp simultaneously on a single system. 
Considerations:
- Insights Tasks (preupgrade and upgrade) currently allow multiple executions on the same system
- The absence of a filter/tooltip in the Insights user interface makes it challenging to determine if a task is already running on a system.
A simple lock mechanism to prevent concurrent executions using a BSD lock has been implemented (see [1](http://gavv.net/articles/file-locks/#bsd-locks-flock)).
JIRA: https://issues.redhat.com/browse/OAMG-9827
=> Add process locking

.packit.yaml
CentOS 7 is EOM and based on that additional changes have to be made in COPR. Use x86_64 arch for epel7 now only.
=> Packit: drop epel-7-ppc64le chroot

.github/workflows/reuse-tests-7to8.yml, .github/workflows/reuse-tests-8to9.yml, .packit.yaml
- replace the sanity tag by 'tier0' (RHELMISC-3211)
- Update ENV variables for RHUI tests
- Enable upgrade path to 8.10 on AWS
- adjust post_install_script for RHEL 7.9 (moved to TF)
- Use frozen branch for rhel7 downstream testing as RHEL 7 is EOM
=> Packit: Bring all changes from leapp-repository + update GH actions

.readthedocs.yaml
The builds in Read the Docs have been broken for a few months now, because the .readthedocs.yaml is required.
=> Add .readthedocs.yaml fixing builds on RTD

.github/workflows/unit-tests.yml, .packit.yaml, Makefile, leapp/cli/__init__.py, leapp/compat.py, leapp/libraries/stdlib/call.py, leapp/messaging/answerstore.py, leapp/repository/__init__.py, leapp/repository/actor_definition.py, leapp/snactor/__init__.py, res/container-builds/Containerfile.ubi9, res/container-tests/Containerfile.ubi10, tests/scripts/test_audit.py, tests/scripts/test_exit_status.py
This patch enables building on EL9 along with the testing infrastructure and dev environment prepared for EL9 and EL10.
Included changes:
- Enable EL9 builds in packit
- Add build container for EL9
- Add test container for EL10
- Add tests on Python 3.12 on ubi10 (really it's ubi9) unit test GH action
- Update Makefile to include the new containers
- Handle deprecations in Python 3.12
=> Enable building for EL 9 and support Python 3.12

leapp/libraries/stdlib/call.py
updated by @pirat89 
Original implementation of the `_call` function (used by `run` from actors) has been leaking file descriptors per each invocation. So in case an actor executed too many of them during an execution it could reach the limit of allowed opened FDs and the execution failed with `OSError: Too many opened files` error.
There have been actually 2 issues:
* `EventLoop` (alias `select.epoll`) have been called before the fork so the child process inherit the created FD too
* that has not been so big problem actually as the child process always ended before the parent finished the function so this has been closed always safely by OS anyway. But updating it anyway to make it cleaner.
* `stdout` and `stderr` pipes (to consumes content from child process) have been created before …
=> Fix leaking FDs in the run (_call) function 

packaging/leapp.spec
The directory should be owned by the leapp rpm so leapp actors could already use it - or existing leapp repositories packages could install some config files inside already.
=> spec: Introduce /etc/leapp/actor_conf.d/ directory

leapp/snactor/context.py
Introduce the `LEAPP_DEBUG_PRESERVE_CONTEXT` environmental variable. When the variable is set to 1 and the environment has `LEAPP_EXECUTION_ID` set, the `LEAPP_EXECUTION_ID` is not overwritten with snactor's execution ID. This allows the developer to run actors in the same fashion as if the actor was run during the last leapp's execution, thus, avoiding to rerun the entire upgrade process. This, naturally, does not help when the actor has outside dependencies, i.e., it requires the filesystem to be set up in a specific way (e.g. a target container) must be present, e.t.c.
Usage:
1. run `leapp upgrade`
2. if you observe your actor crashing, run `leapp-inspector executions` and pick the latest execution ID
3. do `export LEAPP_DEBUG_PRESERVE_CONTEXT=1 LEAPP_EXECUTION_ID=<id>` where `<id>` is …
=> snactor(run): allow using leapp's execution contexts

setup.py, tests/scripts/conftest.py
This broke all (reasonably recent pytest installations) when snactor was not installed.
Resolves: https://issues.redhat.com/browse/RHEL-74372
=> Remove pytest plugin hook

docs/source/conf.py, man/leapp.1, man/snactor.1, packaging/leapp.spec
This is the last Python 2.7 compatible release. Putting Py2 on its earned rest, all the code is going to keep Python 3.6 compatibility. In the same time we are going to stop the testing and building on RHEL 7.
- Bump leapp-framework to 6.0 (#870)
- Bump leapp-framework-dependencies to 6 (#870)
- Require PyAML (on RHEL 7) and python3-PyYAML (on RHEL 8) packages (#870)
- Introduce /etc/leapp/actor_conf.d/ in the leapp rpm (#885)
- Increase soft limits on the number of opened file descriptors and maximum size of manipulated files during initialization (#887)
- [Tech preview] Introduce configurability for leapp actors (#870)
- snactor(run): allow using an existing execution context in used leapp.db (#873)
- [Tech preview] Introduce `api.retrieve_config` function to obtain configuration for …
=> Release 0.19.0

leapp/actors/config.py
Leapp recognized two file extensions for its configuration files: .yaml and .yml. This patch removes the recognition of .yml to avoid user confusion, e.g., creating configuration files with the same name but different extensions. This patch also enforces our documentation to use only one extension.
=> configs: recognize only the .yaml file extension

leapp/utils/clicmd.py, packaging/leapp.spec
When specifying an option for a leapp CLI command using @add_option decorator, it has not been possible to specify a "falsy" value (or let's say empty) as `default` e.g. empty string, empty list, etc. Start to check NoneType for the `default` parameter properly to allow it to set this.
**Bump leapp-framework to 6.1.**
Note:
The similar problem is for `choices` and `metavar` parameters. In case of `metavar` it's however ok to ignore empty string. In case of empty `choices` it would lead to the same evaluation as in case of NoneType (any input is ok). So I that the `default` is the only parameter that needs to be checked properly.
jira: RHEL-86206
=> Fix CLI: allow to set falsy values as default

.packit.yaml
This commit updates the tag and env for the sanity-810to94-aws job to make it run correctly.
=> Update .packit.yaml to fix failing rhui job
